### ISSUE TITLE
Does Migrate Games function still support "change location"?

### ISSUE THREAD

**Issue by Kethers** [CollapseLauncher/Collapse#105]
I use the "4. Migrate Existing Game" function in the wiki, and the tutorial steps show that there will be a pop-up window for user to "Use default Directory" or "Yes, Change location". However the pop-up window doesn't show up and the game stays where it was.

Region: Mainland China

**Comment by Kethers** [comment]
Game: Honkai Impact 3rd

**Comment by Kethers** [comment]
Game: Honkai Impact 3

The game installed via official game launcher was in a different disk.

**Comment by neon-nyan** [comment]
Hi @Kethers,
Sorry for the late response on this.
Currently, the "Change Location"  option is not available in recent version and apologize that the references included in wiki are mostly outdated.

As a workaround for you, if you want to move your game into different disk, please move the entire "Games" folder or just leave it as is if you don't want to move it, then run Collapse. Click on "Install Game" -> "Locate Directory" -> Locate to the "Games" folder, then Collapse should automatically detect it.

**Comment by Kethers** [comment]
Thanks for the reply and your great work to this project. Migrating games mannually is not a hard work so currently unavailable would not be a big deal. Instead I think Taskbar Residence (just like official launcher) is more important. Hope you can add it in todo list.
Best wishes. :)

**Comment by bagusnl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move Game Installation Feature missing](https://trello.com/c/Q26P0vVj/10-move-game-installation-feature-missing)

**Comment by bagusnl** [comment]
Heya!

Game migration is now available (it has been a while but i forgot to update this thread sorry) on Preview branch, you can test it out and if you seen any problem you can reopen this issue or create a new issue

Thank you for the bug report! <3
