### ISSUE TITLE
[Language Tracking] Localization Requests

### ISSUE THREAD

**Issue by Cryotechnic** [CollapseLauncher/Collapse#146]
Heyo!

Thanks for taking interesting in our project! Starting from Collapse 1.70.0, we are officially transitioning to [Transifex](https://explore.transifex.com/collapse-launcher/collapse-mainapp/) for localizing our app. This has the added functionality of managing all our locales in one place and allowing us to quickly deploy locale fixes to the launcher, without having to ping people in GitHub's Issues. 

With the addition of multiple new languages, we felt that now was the best time to migrate. This allows us to better serve our userbase while also working on exciting new features for the launcher. This change means that any PR for locale changes will be closed and the user which did so will be referred to this issue and/or the [Transifex](https://explore.transifex.com/collapse-launcher/collapse-mainapp/) localization project.

Thank you for supporting our work and using our launcher!

Edit June 9 2023: Should you want to request the addition of a new locale for Collapse, please post it here! Any open issues regarding this will be closed and referred to this one. Thanks!

Edit September 30th, 2023: Moved to Transifex for our localization platform

**Comment by Cryotechnic** [comment]
# Currently planned additions as of 2023-06-11
- Russian
- Traditional Chinese

This will be updated in the future for tracking purposes.

**Comment by Heruzinyo** [comment]
Could you add Brazilian Portuguese (pt-BR) to Crowdin? I would like to help (*´▽`*)

**Comment by neon-nyan** [comment]
Hi @Heruzinyo,

Thank you for your interest for translating Collapse and apologize for our late response due to RL events.
We've just added the translation section for Brazilian Portuguese to Crowdin.

Let us know if you need any further help.

![YATTA](https://media.discordapp.net/stickers/1100251678684479528.png?size=240)

**Comment by vitalitk** [comment]
Hello, I'd like to see Ukrainian to make the list as well! Willing to help as a native speaker :)

**Comment by bagusnl** [comment]
> Hello, I'd like to see Ukrainian to make the list as well! Willing to help as a native speaker :)

Hi @vitalitk !

Thank you for your interest in localizing Collapse Launcher to your native language ❤️. We have accepted the requested language `ru_UA` in Transifex! Please check it over at https://app.transifex.com/collapse-launcher/collapse-mainapp/translate/#ru_UA/a1feee4ba9ac2792f77155b065f228cf/472755478

**Comment by vitalitk** [comment]
> > Hello, I'd like to see Ukrainian to make the list as well! Willing to help as a native speaker :)
> 
> Hi @vitalitk !
> 
> Thank you for your interest in localizing Collapse Launcher to your native language ❤️. We have accepted the requested language `ru_UA` in Transifex! Please check it over at https://app.transifex.com/collapse-launcher/collapse-mainapp/translate/#ru_UA/a1feee4ba9ac2792f77155b065f228cf/472755478

Hi,
The locale you added was Russian (Ukraine). I don't think there's a need for it since there's already an existing translation for Russian (though if you want I can still fill it in). The locale for Ukrainian is either "uk" or "uk_ua". Doesn't matter which, since both lead to the same thing. Thanks and sorry for the inconvenience!

**Comment by Cryotechnic** [comment]
Closing as I believe most users now go directly through Transifex to request new locales.
