### ISSUE TITLE
Keyboard shortcuts for switching between games

### ISSUE THREAD

**Issue by jericjan** [CollapseLauncher/Collapse#151]
I've found it a little annoying that I have to click on four things just to switch games. It'd be nice to have some sort of shortcut that makes it faster. Like, Ctrl+1 to switch to Honkai Impact, and Ctrl+3 to switch to Honkai: Star Rail.

**Comment by bagusnl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Keyboard Shortcut](https://trello.com/c/T4KAsZmC/7-keyboard-shortcut)

**Comment by Cryotechnic** [comment]
Implemented as of 1.72.4.
