### ISSUE TITLE
[Request] Please add the possibility of a quick change of games

### ISSUE THREAD

**Issue by DarkAssassin48** [CollapseLauncher/Collapse#198]
Please add the possibility of a quick change of games. 
What could be enabled in the Collapse settings and make it possible to launch the game with one click on the icon.
Here is an example of how I see it. I play 2 games and constantly switch between them.
![CollapseLauncher_15(03-28-51)](https://github.com/neon-nyan/Collapse/assets/40138340/7410c569-9e78-4cc9-b650-f477d9ebfebe)

**Comment by bagusnl** [comment]
Related #133 and #151

**Comment by bagusnl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Games/Region Switching Enhancements](https://trello.com/c/03V8drWN/5-games-region-switching-enhancements)

**Comment by bagusnl** [comment]
For keyboard shortcut that helps with this has already been pushed to Preview. You can use Ctrl+(1-3) to select between games. For the icon selector UI it has not been implemented yet, so the issue stays open

**Comment by minhngoc25a** [comment]
The Starward launcher is a fork of Collapse that implemented the icon selector UI. Perhaps you guys can consult the code there to see which part can be implemented to Collapse?

**Comment by bagusnl** [comment]
> The Starward launcher is a fork of Collapse that implemented the icon selector UI. Perhaps you guys can consult the code there to see which part can be implemented to Collapse?
We will look into it, currently we are tidying up the backends after the .NET 8 migration.

Moved to discussion #340 to better track this
