### ISSUE TITLE
[Bug]: Crash on switching game during switching in progress

### ISSUE THREAD

**Issue by fixator10** [CollapseLauncher/Collapse#228]
### Affected Version

1.70.14 Stable

### Bug Behavior

I switched from Honkai Impact 3rd (Global) to Genshin Impact (Global), and during switching (while the notification at the bottom is shown) switched again to Honkai: Star Rail (Global).
The launcher errored out.

### Expected Behavior

Launcher stops switching to previous region/game and switches to new, without crashing.

### Steps to reproduce

1. Run launcher.
2. Switch to another game.
3. While switch in progress, switch to another one.

### Screenshot(s)

![Crash screen](https://moeka.is-a-good-waifu.com/RLLhAww.png)

### Additional Information

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage, HttpCompletionOption, CancellationToken)
   at Hi3Helper.Http.Http.GetSessionAsStreamAsync(String URL, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken Token)
   at Hi3Helper.Http.Http.DownloadFromSessionStreamAsync(String URL, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken)
   at CollapseLauncher.MainPage.FetchLauncherDownloadInformation(CancellationToken Token, PresetConfigV2 Preset)
   at CollapseLauncher.MainPage.TryLoadResourceInfo(ResourceLoadingType resourceType, PresetConfigV2 preset)
```

**Comment by bagusnl** [comment]
Thanks for submitting a bug report!

Is this a one-time issue or a consistent one ? I personally can't reproduce it locally using either Stable or latest Debug builds

**Comment by fixator10** [comment]
Its reproducible, but kinda hard to reproduce. Its triggered when "changing region" pill is at the bottom of the screen. Im on pretty much old system (AMD Athlon II X3 with HDD), so i was able to trigger it again it by cleaning up images via settings.
https://github.com/neon-nyan/Collapse/assets/11073934/926de70d-49a1-414d-9a97-f46978e8f108

This also can be related to ocasional doubleclicks of my mouse


And just now trying to reproduce it i managed to crash launcher entirely with the same steps...

**Comment by bagusnl** [comment]
Hi, sorry for quite a late reply.

We have identified the issue for this report. It seems that when internet/CPU can't keep up with rapid region switches, it queues up all the functions for region change and finish it frantically while the other functions is not completed doing its thing. 

Current workaround is to wait for the region change to finish, while we looking for a better fix.

**Comment by bagusnl** [comment]
Fix proposal:
Disable "Change Region" button when a region is loading. With that, also always make the "Cancel" button always appears to stop region from loading instead of waiting for 20s.
