### ISSUE TITLE
[Bug]: Unable to access homepage

### ISSUE THREAD

**Issue by yukiryo** [CollapseLauncher/Collapse#252]
### Affected Version

1.71.8

### Bug Behavior

After launching the launcher it will pop up that your internet connection has been disconnected, clicking on the Paimon will instantly pop it up again

### Expected Behavior

Normal access to the homepage

### Steps to reproduce

launch the launcher

### Screenshot(s)

![image](https://github.com/neon-nyan/Collapse/assets/58250223/2c988dbe-781d-432b-997a-88ce8fca7c94)
![image](https://github.com/neon-nyan/Collapse/assets/58250223/b4d9cb7e-7958-44fd-bec8-9bbf13f5fc01)

**Comment by muscularcandy67** [comment]
Thank you for reporting the issue. When trying to reload a loading bar should appear, try to click on cancel as fast as you can and then try to switch to every other game/region to make sure the issue is localized on a single game/region or not

**Comment by bagusnl** [comment]
After doing what @muscularcandy67 said, can you send the content of the stampv2.json inside Collapse's AppData _metadata folder?
To go to Collapse data folder, go to App Settings->Open App Data Folder

**Comment by NishikiAsumi0** [comment]
@bagusnl the content of stampv2.json
```json
{
  "LastUpdated": 202308272217
}
````

**Comment by NishikiAsumi0** [comment]
it only happens on the china mainland server of star rail

**Comment by bagusnl** [comment]
can you try running this build instead?
just simply extract them anywhere and run CollapseLauncher.exe

**Comment by NishikiAsumi0** [comment]
it now works correctly. btw it requires .net7 runtime to launch at the first time

**Comment by muscularcandy67** [comment]
It requires .net 7 to run everytime

**Comment by akatsukiro** [comment]
> it only happens on the china mainland server of star rail

Same.

**Comment by bagusnl** [comment]
@akatsukiro can you send your log or exception message here?

**Comment by bagusnl** [comment]
> sorry about late response. Today it works fine, and how can I find the log file?
@akatsukiro It seems from your error message its probably some mihoyo CDN hiccup in your area. If you get the same issue again and constantly, please make a new ticket since we are closing this one due to stale and no response from the OP.

For the log file, its under Collapse data folder (you can access by going to Collapse settings and pressing the "Open App Data Folder". The log file is on `_logs` subfolder and formatted by the date you open the launcher.
