### ISSUE TITLE
[Request] Redownload game background feature

### ISSUE THREAD

**Issue by jericjan** [CollapseLauncher/Collapse#264]
**Is your feature request related to a problem? Please describe.**
My game updated the background and it seems to have failed midway. It looks like this:  
![](https://i.imgur.com/14HSIV7.png)

**Describe the solution you'd like**
A button that lets you redownload the image.

**Describe alternatives you've considered**
I can delete the image in `AppData\LocalLow\CollapseLauncher\GameFolder\_img\bg` and restart the launcher, and it redownloads it.

**Additional context**
N/A

**Comment by muscularcandy67** [comment]
Thank you for reporting the issue. Actually we are already aware of this issue and if memory doesn't fail me somewhere there is a commit that handles that scenario in the background without having you click any button. It just wasn't pushed yet to any release build (stable/preview)

**Comment by bagusnl** [comment]
Fix proposal:
Implement a check in the background (after the BG has been displayed) if the downloaded BG is not downloaded correctly (has less size than the remote response). When true, delete the image on close (deleteOnClose) so it will be redownloaded on next restart or region load.

**Comment by Cryotechnic** [comment]
Fixed as of next stable release.
