### ISSUE TITLE
[Request]: If in a metered network environment, pause automatic updates for Collapse

### ISSUE THREAD

**Issue by DeepChirp** [CollapseLauncher/Collapse#286]
### Is your request related to a problem?

No

### Describe your proposed solution

When starting, first check if the current network is a metered network, and if so, stop checking for updates. At the same time, like Microsoft Edge, Collapse can also provide a switch that allows users to automatically detect and download updates under such network conditions.

### Describe alternatives you've considered

_None_

**Comment by bagusnl** [comment]
Thank you for sending enhancement request for Collapse Launcher!

We have processed your request and will apply this enhancement proposal:
# Enhancement Proposal
## Skip update check if the network is metered
Use NetworkHelper's NetworkCostType and see if its either Unrestricted or Unknown, if yes then go ahead to do the usual update routine, if not skip the current update check and do another check in the usual time.
Refs:
(Note these are UWP refs, no WinUI refs found but should be similar enough)
- https://learn.microsoft.com/en-us/uwp/api/windows.networking.connectivity.networkcosttype?view=winrt-22000
- https://learn.microsoft.com/en-us/previous-versions/windows/apps/hh750310(v=win.10)
Location: https://github.com/CollapseLauncher/Collapse/blob/e1ac2a3288f83ce64d8e56fe08d3561f794053df/CollapseLauncher/Classes/EventsManagement/EventsHandler.cs#L31

**Comment by DeepChirp** [comment]
At the same time, I believe that when checking for updates in a metered network, users should be reminded that this may incur additional fees.

**Comment by bagusnl** [comment]
So, with this proposal, the entire automated update check sequence for the launcher itself (metadata update will still occur due to the importance of it) will be skipped. The only way to update on metered connection is to manually pressing the `Check for Update` button in the settings page, as it will trigger forceUpdate mechanism that skips all checks.
As the forceUpdate can only be triggered manually, in my opinion there is no need to add another warning as clicking the button is most likely intentional.

What do you think?

**Comment by DeepChirp** [comment]
> So, with this proposal, the entire automated update check sequence for the launcher itself (metadata update will still occur due to the importance of it) will be skipped. The only way to update on metered connection is to manually pressing the `Check for Update` button in the settings page, as it will trigger forceUpdate mechanism that skips all checks. As the forceUpdate can only be triggered manually, in my opinion there is no need to add another warning as clicking the button is most likely intentional.
> 
> What do you think?

This situation is reasonable. But there is another situation where users may forget that the network they are using is metered. I think it's necessary to remind in this situation. What do you think?

**Comment by bagusnl** [comment]
Sure does, we can create a SimpleDialog that is only triggered when metered connection is up

**Comment by DeepChirp** [comment]
> Sure does, we can create a SimpleDialog that is only triggered when metered connection is up

Good idea. Thank you for your quick respond!
