### ISSUE TITLE
[Bug]: Genshin(China) Game Settings Crash

### ISSUE THREAD

**Issue by misaka10843** [CollapseLauncher/Collapse#295]
### Affected Version

1.71.15-Stable & 1.72.5-PRE

### Bug Behavior

In 1.71.15, clicking on the game Settings after switching to Genshin-China will cause an error, while in 1.72.5-PRE it will flash back directly

（the system is WTG）

### Expected Behavior

In theory, it should display the Game Settings page

### Steps to reproduce

1. change the area service to Genshin Impact - Mainland China
2. Click game Settings
3. bug appearance

### Screenshot(s)

![unknown_2023 10 16-11 14](https://github.com/CollapseLauncher/Collapse/assets/69132853/5bfaf226-7736-4d0b-8bd0-0a26baa8c9ef)

### Additional Information

[DxDiag.txt](https://github.com/CollapseLauncher/Collapse/files/12911740/DxDiag.txt)
[log-2023-10-16-sta1.71.15-id1.log](https://github.com/CollapseLauncher/Collapse/files/12911742/log-2023-10-16-sta1.71.15-id1.log)
[log-2023-10-16-pre1.72.5-id1.log](https://github.com/CollapseLauncher/Collapse/files/12911743/log-2023-10-16-pre1.72.5-id1.log)

**Comment by bagusnl** [comment]
Eyyo, thanks for reporting issue in Collapse!

Can you try going to the game then change the bloom setting there? Make sure to exit from the settings menu first and then close the game safely. After that, open Game Settings menu in Collapse and see if the problem persist.

If it does, please export your Genshin's registry which contains GENERAL_DATA_X key. Since this export might contain sensitive data, you can send them to my email bagusnl@protonmail.com

**Comment by misaka10843** [comment]
> Eyyo, thanks for reporting issue in Collapse!
> 
> Can you try going to the game then change the bloom setting there? Make sure to exit from the settings menu first and then close the game safely. After that, open Game Settings menu in Collapse and see if the problem persist.
> 
> If it does, please export your Genshin's registry which contains GENERAL_DATA_X key. Since this export might contain sensitive data, you can send them to my email [bagusnl@protonmail.com](mailto:bagusnl@protonmail.com)

Probably because genshin's image quality Settings are not yet available in the registry (the new system has not been opened once). 

However, it is always prompted to open the game once instead of reporting an error/flash back

**Comment by bagusnl** [comment]
Ah, I see. We have implemented such behavior when the loading fails to show an error page showing "Please open the game" or something similar. I think the error got overridden by other exception catcher. Will investigate further

**Comment by bagusnl** [comment]
The fix for this issue is included in PR 302 by Shatyuka which contains other fixes related to GI Settings page.

Thank you for reporting this issue !
