### ISSUE TITLE
[Request]: Add the ability to minimize Collapse by clicking taskbar icon

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#311]
### Is your request related to a problem?

No

### Describe your proposed solution

When Collapse is in the foreground, allow the user to click Collapse's taskbar icon to minimize the launcher, similar to how many other programs behave.

### Describe alternatives you've considered

Clicking the minimize button on the launcher's interface.

### Additional context

https://github.com/CollapseLauncher/Collapse/assets/88598340/c9ae86cb-b47d-40fc-acb8-d3db4919f08a

**Comment by bagusnl** [comment]
Currently the click command is used to bring Collapse windows to foreground as shown in here

https://github.com/CollapseLauncher/Collapse/blob/net-8/CollapseLauncher/XAMLs/MainApp/TrayIcon.xaml#L15-L17

We could make it so that it toggles all Collapse' windows minimized-visible instead

**Comment by bagusnl** [comment]
Will do an internal discussion for this

**Comment by bagusnl** [comment]
Eyyo~ sorry for taking awhile to reply back.

After talking with the team, we have concluded that at the current state we will not change how TrayIcon click behaviors works as we observed by other apps that uses tray icon. Though in the meantime we added both ability to minimize Collapse to tray using the Minimize button (configurable in Settings), and also tooltip popup to give a little reminder on how the control works for tray icon.
![image](https://github.com/CollapseLauncher/Collapse/assets/28079733/a81a3b76-62d7-41db-b2e6-7792ec0b5ef8)

![image](https://github.com/CollapseLauncher/Collapse/assets/28079733/9e05b3ed-079c-4e57-8b41-07aa46c04b3b)

Feel free to close this ticket if you agree with our current solution, or send me a heads up if you don't

**Comment by bagusnl** [comment]
Oh, my bad, I completely mixed up the two xD. Will look into it.

> I think that it would be more user-friendly if it was labeled something along the lines of "[Window?] minimize button behavior" as I was personally a bit confused at what it meant at first until I actually tried it out, but that could be just me.
I'm still not fully convinced with it either, but for the Settings page one I think "Minimize to Tray" is fine as is. But for the tray popup help message I'm still open for suggestion. Though it's kinda hard because it's limited to certain number of chars per line, and the 3rd line already on the limit of it.

**Comment by Scighost** [comment]
Cannot minimize window by clicking task bar icon because the window style removed `WS_MINIMIZEBOX`.

https://github.com/CollapseLauncher/Collapse/blob/500c6a61f02a6f38a33eb342ca9bd1b693c633ff/CollapseLauncher/XAMLs/MainApp/MainWindow.xaml.cs#L163

**Comment by bagusnl** [comment]
> Cannot minimize window by clicking task bar icon because the window style removed `WS_MINIMIZEBOX`.
I don't recall why it was used before though currently we used it to hook with the `Minimize to Tray` function

**Comment by shatyuka** [comment]
> Cannot minimize window by clicking task bar icon because the window style removed `WS_MINIMIZEBOX`.
> 
> https://github.com/CollapseLauncher/Collapse/blob/500c6a61f02a6f38a33eb342ca9bd1b693c633ff/CollapseLauncher/XAMLs/MainApp/MainWindow.xaml.cs#L163

This line is used to hide the system buttons, especially the maximize button.
To fix the task bar issue, we need to hide the title bar completely and handle minimizing, closing and dragging inside app. I'm working on it.

**Comment by bagusnl** [comment]
The fix will be included in next preview release (1.72.7) tracked here #309
