### ISSUE TITLE
[Minor Bug]: Adjust alignment of "Voice Over Language" and "Mute Audio" in the Honkai Impact 3rd settings panel

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#333]
### Affected Version

Collapse v1.72.10 Preview

### Bug Behavior

In the small window size configuration, the "Voice Over Language" and "Mute Audio" titles are practically touching each other.

### Expected Behavior

The titles could be equally distant as they are in the large window size configuration — there is plenty of horizontal space to do so.

### Steps to reproduce

1. Open Collapse's settings panel
2. Change Collapse's window size to `Small`
3. Open Honkai Impact 3rd's settings panel
4. The "Voice Over Language" and "Mute Audio" titles are touching

### Screenshot(s)

![image](https://github.com/CollapseLauncher/Collapse/assets/88598340/8bd1feb4-19ba-4e60-8ab3-1f853159c3ab)
![image](https://github.com/CollapseLauncher/Collapse/assets/88598340/a1e300a9-1567-4465-b0dd-dd1fc33a2dcd)

### Additional Information

I don't know if there is a mute option for the other miHoYo games, but I can confirm that this is a visual problem for Honkai Impact 3rd.

**Comment by bagusnl** [comment]
Eyyo~
Thank you for submitting bug report and sorry for taking quite a long time to come around and look at this.

I have fixed this by making the mute audio section centers in its region.
Here's how it looks on small window
![image](https://github.com/CollapseLauncher/Collapse/assets/28079733/1b237a5b-d789-41b2-988f-700b98a4b6ae)

and here is how it looked on normal window
![image](https://github.com/CollapseLauncher/Collapse/assets/28079733/fe5eb9e1-05d4-473b-a95f-b68cecc6cee0)

The fix will come on next preview version, possibly sometime after either Genshin or HSR update
Sorry for the inconvenience and thanks again for reporting~
