### ISSUE TITLE
[Bug]: Unable to completely uninstall launcher

### ISSUE THREAD

**Issue by 435201823** [CollapseLauncher/Collapse#345]
### Affected Version

1.71.16

### Bug Behavior

If the launcher has been upgraded through [Squirrel], uninstalling it will result in incomplete uninstallation.
Because Squirrel will save up to two versions of the program, only the one filled in iss will be uninstalled when uninstalling.

### Expected Behavior

Complete uninstall

### Steps to reproduce

1. install Collapse 1.71.14
2. Upgrade to version 1.71.16 via Squirrel
3. uninstall

### Additional Information

I am developing a program. I referred to Collapse's installation and upgrade solution, using Inno setup + Squirrel, but there has been a problem with the uninstallation part. I found that Collapse also has the same problem. The method I'm currently thinking of is to uninstall via squirrel since it uninstalls completely.

**Comment by 435201823** [comment]
I changed the solution:

1. Prevent Squirrel from modifying the registry and ensure that users cannot uninstall through Squirrel
```
mgr.RemoveUninstallerRegistryEntry();
```

2. Add this to iss
```
[UninstallDelete]
Type: filesandordirs; Name: "{app}\*"
```

**Comment by bagusnl** [comment]
Heyyooo~

Thank you for your insight on the situation, @neon-nyan currently rewriting the parser and rewirter for the innosetup stuff so I'll redirect your suggestion into him.

Due to IRL situation, he might unable to reply in timely manner so we'll wait.

Thank you again! <3
