### ISSUE TITLE
[Request]: Add support for Genshin Impact FPS unlocker

### ISSUE THREAD

**Issue by farsdewibs0n** [CollapseLauncher/Collapse#346]
### Is your request related to a problem?

No

### How is the feature request related to the problem?

Adds the ability to run Genshin Impact above 60fps using external tool.

### Describe your proposed solution

By adding the integration of this project
https://github.com/34736384/genshin-fps-unlock

### Describe alternatives you've considered

I know this can break the game's ToS, but having this as an option would be good. If this proposal got refused, then fine by me.

**Comment by bagusnl** [comment]
Hi! Thank you for submitting enhancement request for our project!

Unfortunately, due to inherent risk of the Genshin FPS unlocking method (direct memory read/write), we can not implement said feature. For further read, you can go to my comment on the other thread at the link below

https://github.com/CollapseLauncher/Collapse/issues/104#issuecomment-1510430982

Thank you for your understanding!

**Comment by nickelberg** [comment]
@farsdewibs0n
You can somewhat achieve this **unofficially** and **on your own risk.**
Using this method, you can even add more/other software to run before running Genshin like GIMI, DXVK libs, ReShade etc. (may require modification)
- Advanced settings - **Enabled ✅**
- Commands to be executed before the game is launched - **Enabled ✅**
- Force exit launched process when Game is closed/stopped - **Disabled ⛔**

Code:
`powershell.exe -Command "$unlockerpath='C:\Genshin Impact FPS Unlocker'; cd $unlockerpath; while (-not (Get-Process -Name 'GenshinImpact' -ErrorAction SilentlyContinue)) { Start-Sleep -Seconds 1 }; Stop-Process -Name 'GenshinImpact' -Force; (Get-Process -Name 'unlockfps_nc' -ErrorAction SilentlyContinue) | Stop-Process -Force; Start-Process \"$unlockerpath\\unlockfps_nc.exe\""`

**You only need to change "$unlockerpath='C:\Genshin Impact FPS Unlocker" to your own path where you copied/downloaded fps unlocker (unlockfps_nc.exe)**

![launcher_options](https://github.com/user-attachments/assets/3b514fa0-eb41-4d6a-a8f4-1ffdfcf72826)

Problems I noticed with this method:
- Collapse Launcher doesn't count play time correctly
