### ISSUE TITLE
[Bug]: Game crashed when launching StarRail

### ISSUE THREAD

**Issue by infinity8942** [CollapseLauncher/Collapse#347]
### Affected Version

1.71.16

### Bug Behavior

StarRail.exe crashed when using Collapse

### Expected Behavior

game works fine

### Steps to reproduce

1.start game by using Collapse
2.game crashed when loading
3.start game by using official launcher
4.game works fine

### Screenshot(s)

![微信截图_20231224103151](https://github.com/CollapseLauncher/Collapse/assets/3975899/b8c60b72-c980-4f13-a663-cc59f55bf851)

### Additional Information

[main_2023-12-24.log](https://github.com/CollapseLauncher/Collapse/files/13760725/main_2023-12-24.log)

**Comment by bagusnl** [comment]
Heyyo~ Thank you for submitting bug report for Collapse!

From the official launcher log file you have sent, official launcher flagged data.unity3d as corrupted. Before you switched to official launcher, have you tried doing game repair?

also for confirmation, is the HSR region you were trying to run is on Mainland China or Bilibili? @infinity8942 



<+++++>
CC @neon-nyan @shatyuka 

The file md5 on the log stated that the plugin was installed with its correct hash but the official launcher flagged it as corrupted and also the game wont start. This behavior is quite interesting to say the least and is consideration for our PR over at #342 

Judging from the hashes, the game region is `HSRCN`
### pkgversion
> `{"remoteName": "StarRail_Data/data.unity3d", "md5": "ee13471ab02aedbb59acfb26c48f7490", "fileSize": 21710086}`

### plugin api
> `"validate": "[{\"path\":\"StarRail_Data/data.unity3d\",\"md5\":\"92b75aff77304b851333dbce94730eab\"}]"`

**Comment by shatyuka** [comment]
Try CI build https://github.com/CollapseLauncher/Collapse/actions/runs/7262750999

**Comment by infinity8942** [comment]
Thanks for your response. yes I'm at Mainland China and I did try to do the game repair this moring, but the result was same at that time.
Now It's running fine, and I don't know why... I just hope it can help you to impove Collapse.

**Comment by bagusnl** [comment]
I have put the change that *knock on wood* should fix this behavior on https://github.com/CollapseLauncher/Collapse/commit/3ef9f3781b5e2d6eac9b967169d35a866ce9f859
Since this issue seems to be quite random, we will close this for now and feel free to reopen or put another ticket shall this issue reappears.

Thank you for the bug report!
