### ISSUE TITLE
[Bug]: HSR wrong voice pack

### ISSUE THREAD

**Issue by shimizu-izumi** [CollapseLauncher/Collapse#365]
### Affected Version

1.72.14

### Bug Behavior

I selected Japanese as the voice language I wanted to install, but Korean was installed instead.

### Expected Behavior

It should have installed the correct voice language for HSR global

### Steps to reproduce

1. Uninstall HSR global (if installed)
2. Install HSR global and select Japanese as the voice language
3. Open the game and go into the settings, the Korean voice language should be installed instead of Japanese.

**Comment by Cryotechnic** [comment]
Hi, this is currently a known issue and a commit resolving this has been pushed (6fef7a5), which hopefully addresses the issue. We'll be releasing a launcher update shortly to fully resolve the issue.

Thanks for bringing this up to our attention!

**Comment by bagusnl** [comment]
The update that should fix this issue is up. Please update your Collapse client.
Let us know if the problem still exist, you may reopen the issue ticket.

Thank you for reporting this issue to us!
