### ISSUE TITLE
[Known Bug]: Temporarily Disabling Repair/Cache/Delta Patch Features for HI3 7.3.0+

### ISSUE THREAD

**Issue by bagusnl** [CollapseLauncher/Collapse#383]
### Affected Version

All

# Notice

Due to the number of changes happened in the backend, currently Collapse Launcher does not support some of our main features for Honkai Impact 3rd 7.3.0 update:
- Game Repair
- Cache Update
- Delta Patch

@neon-nyan currently working on the fix but due to IRL issues this fix might come at a later date.

Any other features should work fine. Features like updating, game settings, and generally launching the game. If something is not working as intended, please don't hesitate to send us issue ticket!

We are sorry for the inconvenience caused by the feature disablement in this update.
Thank you for your continuous support <3

- Collapse Launcher Team

**Comment by neon-nyan** [comment]
Hi there,
This issue has been fixed as per latest update, 1.73.4 for both Stable and Preview releases.
Please make sure you have your launcher up-to-date to receive the fix and some new features.

Closing this issue for now.
