### ISSUE TITLE
[Bug]: Collapse crashes sometimes, when PAC script is using (Windows)

### ISSUE THREAD

**Issue by NiTiSon** [CollapseLauncher/Collapse#387]
### Affected Version

1.73.1-pre

### Bug Behavior

(Sometimes) when I try to launch Collapse with the enabled PAC script, they crash (the window is shown, but closes then)

It will not be crash, if I launch it with enabled PAC script after I launched it successful with disabled PAC script

[DxDiag.txt](https://github.com/CollapseLauncher/Collapse/files/14143909/DxDiag.txt)

By path "C:\Users\%username%\AppData\LocalLow\CollapseLauncher\_logs" no log files found

### Expected Behavior

Launch, show the error window maybe
Obviously not crash

### Steps to reproduce

1. Try to launch - the window displays for 0.5 sec, then closed
2. Disable the PAC script in Windows Proxy options
3. Try to launch - success

### Screenshot(s)

https://github.com/CollapseLauncher/Collapse/assets/60577131/7a052130-d2a8-4dad-8052-1605a334a45f

### Additional Information

I'm using [prostovpn PAC script](https://antizapret.prostovpn.org/proxy.pac) for access to blocked in russia sites

**Comment by bagusnl** [comment]
Hi~

Please attach Collapse Log file that stated the crash. If its not available, check Event Viewer for APPCRASH event relatsd to Collapse

**Comment by NiTiSon** [comment]
> Hi~
> 
> Please attach Collapse Log file that stated the crash. If its not available, check Event Viewer for APPCRASH event relatsd to Collapse

As I mention earlier, I didn't find any log files inside `C:\Users\%USERNAME%\AppData\LocalLow\CollapseLauncher` (there are no logs' directory too)

Faulting application name: CollapseLauncher.exe, version: 1.73.1.0, time stamp: 0x65410000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3930, time stamp: 0x9141f979
Exception code: 0xc000027b
Fault offset: 0x000000000012db22
Faulting process id: 0x31d0
Faulting application start time: 0x01da560312fcce43
Faulting application path: C:\Apps\Collapse\app-1.73.1\CollapseLauncher.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: d3a2508c-19bb-4fc0-b1a6-0b99415b24a0
Faulting package full name: 
Faulting package-relative application ID:

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-02-02T18:10:18.5245979Z" /> 
  <EventRecordID>34555</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>USSR-PC</Computer> 
  <Security /> 
</System>
<EventData>
  <Data>CollapseLauncher.exe</Data> 
  <Data>1.73.1.0</Data> 
  <Data>65410000</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.3930</Data> 
  <Data>9141f979</Data> 
  <Data>c000027b</Data> 
  <Data>000000000012db22</Data> 
  <Data>31d0</Data> 
  <Data>01da560312fcce43</Data> 
  <Data>C:\Apps\Collapse\app-1.73.1\CollapseLauncher.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>d3a2508c-19bb-4fc0-b1a6-0b99415b24a0</Data> 
  <Data /> 
  <Data /> 
</EventData>
</Event>
```

**Comment by bagusnl** [comment]
Sorry for not stating before, but the log files is not located in AppData 
You can get to the folder by opening the Collapse and go to App Settings, then scroll down to get into the "Open App Data folder", on that folder, go to `_logs` folder. There lies the log files from the app

**Comment by Cryotechnic** [comment]
Closing for now as it has been more than a month since the user has posted, without any replies.
