### ISSUE TITLE
[Request]: Customize the launcher

### ISSUE THREAD

**Issue by anzheerdiya** [CollapseLauncher/Collapse#410]
### Is your request related to a problem?

No

### Describe your proposed solution

You can add a custom launcher in quick settings

### Describe alternatives you've considered

I want to give a parameter to view information in the custom startup parameters. https://docs.unity3d.com/Manual/PlayerCommandLineArguments.html

**Comment by anzheerdiya** [comment]
> 嘿，你好
> 
> 感谢您的建议，但我相信您试图描述的是在启动游戏时启用自定义参数？如果是这样，我们已经有了这个功能。您可以通过单击“快速设置”按钮输入参数 - >向下滚动一点并启用“自定义启动参数”开关。然后，在下面，您可以输入要与游戏一起使用的参数。
> 
> ![image](https://private-user-images.githubusercontent.com/30566970/309307455-73034cd6-0185-49f8-8207-72ce24c0eade.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDUxNzEsIm5iZiI6MTcwOTM0NDg3MSwicGF0aCI6Ii8zMDU2Njk3MC8zMDkzMDc0NTUtNzMwMzRjZDYtMDE4NS00OWY4LTgyMDctNzJjZTI0YzBlYWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDAyMDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZmU3ZTBmZGM5MmU0YWYxMDZiOWNmODJlOTBlYzAxZWY3NGJlMjVhY2M3MjNmYmY1ZjgwYjI3OWRlYzE2MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZqhKhy_Jb1FFBJS-vthN8YI7RwSNdV1BYxUd9f9efM)
> 
> 或者，您可以转到“游戏设置”页面 -> 向下滚动并启用“启动参数”开关。然后，您可以执行与我上面提到的相同的操作。
> 
> ![image](https://private-user-images.githubusercontent.com/30566970/309308592-436ac87a-edd6-4224-8e87-18ac5c5ce680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDUxNzEsIm5iZiI6MTcwOTM0NDg3MSwicGF0aCI6Ii8zMDU2Njk3MC8zMDkzMDg1OTItNDM2YWM4N2EtZWRkNi00MjI0LThlODctMThhYzVjNWNlNjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDAyMDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNDNjZmJhNmVhYWE0ZTE0M2YwODJlOGU1YjczYjViMWQ2OGI1YWM1NzljNzU3NGEyNTc3ZWY0ZjM4MmYyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l97RYkqRs7OVlang4Rvs-aIwdbzh9JbV7JQ12nIbP0U)

Sorry I didn't notice, but could you make a custom startup executable like this
![屏幕截图 2024-03-02 101258](https://github.com/CollapseLauncher/Collapse/assets/83170394/84b3056b-d3a2-4824-81fa-30845de73ff7)

**Comment by bagusnl** [comment]
> Sorry I didn't notice, but could you make a custom startup executable like this
> ![屏幕截图 2024-03-02 101258](https://github.com/CollapseLauncher/Collapse/assets/83170394/84b3056b-d3a2-4824-81fa-30845de73ff7)

I could not find any legitimate reason for this feature to be implemented without breaking our own contribution guideline. At most for Collapse case currently, launching other executable can be done either by adding it into Community Tools (for tools like artifact scanner and maps) or pre-launch / post-exit command launch under 'Advanced Settings'.

I'm not sure what the executable you are trying to launch the game with but we currently cannot support doing that without *tip-toeing* HoYo's ToS more
