### ISSUE TITLE
[Bug]: Honkai Impact 3rd Game Settings Error

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#413]
### Affected Version

Collapse v1.73.4 Preview

### Bug Behavior

The following keeps appearing despite following the directions of "open the game, change any settings, then close the game."
![image](https://github.com/CollapseLauncher/Collapse/assets/88598340/7323d1b5-54ff-461a-a99e-dfa43777c929)

https://github.com/CollapseLauncher/Collapse/assets/88598340/2decdcf8-253e-4346-9303-517ad357d4d6

### Expected Behavior

Collapse should be able to read my settings.

### Steps to reproduce

1. Open Collapse in the Honkai Impact 3rd region.

### Related Issues

#411 (?)

### Additional Information

[log-2024-03-01-pre1.73.4-id1.log](https://github.com/CollapseLauncher/Collapse/files/14467453/log-2024-03-01-pre1.73.4-id1.log)

**Comment by bagusnl** [comment]
For workaround, please launch the game directly and change the Reflection Quality settings in game to either Off/Low/High

**Comment by bagusnl** [comment]
The proper fix has been submitted thru https://github.com/CollapseLauncher/Collapse/commit/f73f2ad5dbebea260f917a6f0a81c1d14e8df409

All the new settings has been added as well, we will release the fix on next update~

**Comment by bagusnl** [comment]
Release with fix has been deployed, closing issue~

Thank you for letting us know about the problem!
