### ISSUE TITLE
[Bug]: Error when applying GameBoost

### ISSUE THREAD

**Issue by Caelum008** [CollapseLauncher/Collapse#414]
### Affected Version

1.73.4-Pre

### Bug Behavior

```
System.ComponentModel.Win32Exception (0x80004005): There was an error while trying to launch the game!
	Throw: System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass)
   at CollapseLauncher.Pages.HomePage.StartGame(Object sender, RoutedEventArgs e)
 ---> System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass)
   at CollapseLauncher.Pages.HomePage.StartGame(Object sender, RoutedEventArgs e)
```

### Expected Behavior

Should not be receiving this.

### Steps to reproduce

1. Game repair
2. Checked for new update

**Comment by bagusnl** [comment]
Can you send more details like what OS are you using and if its modified in any way (eg. Custom ISO for the like of Tiny11, AtlasOS, etc) ?

And also did you make sure that Collapse run as admin? It should do that in the first place but just making sure because its saying that access to the process is denied likely when the "Bosst game priority" feature is activated

**Comment by Caelum008** [comment]
> Can you send more details like what OS are you using and if its modified in any way (eg. Custom ISO for the like of Tiny11, AtlasOS, etc) ?
> 
> And also did you make sure that Collapse run as admin? It should do that in the first place but just making sure because its saying that access to the process is denied likely when the "Bosst game priority" feature is activated

sorry for the lack of info.
1. OS is Windows and nope. this is not custom OS. just plain Windows.
2. yes. Collapse is run as admin.

**Comment by bagusnl** [comment]
Can I have your system specs? Mainly:

1. CPU
2. GPU
3. RAM
4. Wheter your Genshin install is on SSD or HDD and the model number for the storage?

**Comment by Caelum008** [comment]
1. CPU: Intel i3 9th Gen
2. GPU: GeForce 710
3. RAM: 8GB
4. Whether your Genshin install is on SSD or HDD and the model number for the storage? - SSD

**Comment by Caelum008** [comment]
> 1. CPU: Intel i3 9th Gen
> 2. GPU: GeForce 710
> 3. RAM: 8GB
> 4. Whether your Genshin install is on SSD or HDD and the model number for the storage? - SSD

I wasn't receiving this error before the latest update. that's why I reported it.

**Comment by bagusnl** [comment]
I see, funny thing about that is, we have not changed anything about it for quite awhile xD

Though, my hypothesis is that the priority adjustment failed because it detected the process too early causing it to have "Access denied" because the process had just spawned.

I will try to fix this by adding a 10s delay to the Game Priority Booster and see if this can help with the situation.

**Comment by lynxxhorizon** [comment]
same issues here, hope it will be fixed soon

**Comment by bagusnl** [comment]
Current workaround for not getting this error is to disabling "Boost Game Priority" in the Game Settings here:
![image](https://github.com/CollapseLauncher/Collapse/assets/28079733/e09237d2-d46e-4903-94b1-746f4b8fbbaf)

I'm currently working on fixing HI3 settings mess so it might take me awhile to get this sorted out

**Comment by Caelum008** [comment]
> Current workaround for not getting this error is to disabling "Boost Game Priority" in the Game Settings here: ![image](https://private-user-images.githubusercontent.com/28079733/309472618-e09237d2-d46e-4903-94b1-746f4b8fbbaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODI0OTcsIm5iZiI6MTcwOTM4MjE5NywicGF0aCI6Ii8yODA3OTczMy8zMDk0NzI2MTgtZTA5MjM3ZDItZDQ2ZS00OTAzLTk0YjEtNzQ2ZjRiOGZiYmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDEyMjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNmI2NTA5ZWVlYTA0MWRkNTYxM2I3NDg1ZTRiNWRlZmI1NmNlOTVjZGNiMjExNDg4NzRkZjVhZTdmYzllMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4lNLsY0nsdwL_ncfz5wuBIUenQVkZ7jyVL4_P-J9004)
> 
> I'm currently working on fixing HI3 settings mess so it might take me awhile to get this sorted out

noted on this. thank you so much!

**Comment by bagusnl** [comment]
Heyya~

I have submitted a commit that tries to fix this here https://github.com/CollapseLauncher/Collapse/commit/5148b3e6a6d9a652171b84b4af96347a6c68f1a4
You can download the nightly build here https://nightly.link/CollapseLauncher/Collapse/actions/runs/8158021629
PS. Dont replace your collapse files, just extract everything and run CollapseLauncher.exe directly. 

Please re-enable the option and also enable Console in the settings. After pressing "Start Game", observe for anything that has `[HomePage::GameBoost_Invoke]` on the start of the line, if it has error, please send the entire log here

**Comment by Caelum008** [comment]
Hi,

I think it has fixed the issue. I'm no longer receiving the error when Boost Priority is on for Genshin when I opened Collapse from the extracted files.

**Comment by bagusnl** [comment]
Alrighty, thanks for the confirmation!
We will push the fix on next update schedule~
