### ISSUE TITLE
[Bug]: Game Repair & Cache Update functions crash w/ small Window Size

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#415]
### Affected Version

Collapse v1.73.4 Preview

### Bug Behavior

Using Collapse in small Window Size will lead to crashes when using the Game Repair and Cache Update functions. This crash appears to occur on all games/regions.

### Expected Behavior

Collapse should not crash upon using the Game Repair and Cache Update functions.

### Steps to reproduce

1. Set Window Size to Small in Collapse's settings
2. Open any regions' Game Repair or Cache Update utility and "Quick Check" or "Full Check"

### Screenshot(s)

https://github.com/CollapseLauncher/Collapse/assets/88598340/160556ab-399a-491d-b048-0288a5ed6524

### Additional Information

[log-2024-03-01-pre1.73.4-id1.log](https://github.com/CollapseLauncher/Collapse/files/14467488/log-2024-03-01-pre1.73.4-id1.log)

**Comment by shatyuka** [comment]
Fixed in 58ca6d0. You can try the latest CI build.

**Comment by shatyuka** [comment]
> It is possible for this to be changed?

will have a look later

**Comment by shatyuka** [comment]
commit eabce3f
ci https://github.com/CollapseLauncher/Collapse/actions/runs/8143398993

**Comment by bagusnl** [comment]
Release with fix has been deployed, closing issue~

Thank you for letting us know about the problem!
