### ISSUE TITLE
[Bug]: Can't launch Collapse 1.73.4 but previous version work (ROG Ally)

### ISSUE THREAD

**Issue by SonicDX12** [CollapseLauncher/Collapse#418]
### Affected Version

Collapse 1.73.4 Stable

### Bug Behavior

Precision: The bug I have is on my ROG Ally only. I don't have the bug on my desktop PC.

I can't launch the new version of Collapse Launcher 1.73.4.
When i launch the program, it's:
- Open a black window (screenshot below)
- Ends directly like a force close.

[DxDiag.txt](https://github.com/CollapseLauncher/Collapse/files/14495060/DxDiag.txt)
[log-2024-03-05-sta1.73.4-id0.log](https://github.com/CollapseLauncher/Collapse/files/14495062/log-2024-03-05-sta1.73.4-id0.log)
[log-2024-03-05-sta1.73.4-id1.log](https://github.com/CollapseLauncher/Collapse/files/14495064/log-2024-03-05-sta1.73.4-id1.log)

Nothing special appears in the logs.

### Expected Behavior

Collapse should have launched normally.
I should have accessed the launcher and launched a game.

### Steps to reproduce

1. Launch the program

### Screenshot(s)

![WinUI Desktop 05_03_2024 12_15_36](https://github.com/CollapseLauncher/Collapse/assets/1226555/b58b20b6-a269-46f1-b2b7-5f84415f5bcd)

### Additional Information

Like I said above, the bug I have is only on my ROG Ally.
On my Desktop PC, the launcher works normally. (And it's a great launcher ! Good job !)
The previous version like the 1.72.18 works normally on my ROG Ally. 

Additionnal information:
If I connect an external display via a USB-C hub to the ROG Ally, the launcher launches normally.

**Comment by shatyuka** [comment]
Don't have permission to access the file

**Comment by SonicDX12** [comment]
Oups ! Forget to change the permission.
You can try now. It’s normally good.

**Comment by shatyuka** [comment]
```
0:000> !clrstack
OS Thread Id: 0x3ea4 (0)
        Child SP               IP Call Site
0000001F3497BB48 00007fff9d4d0a19 [InlinedCallFrame: 0000001f3497bb48] 
0000001F3497BB48 00007fff3d894064 [InlinedCallFrame: 0000001f3497bb48] 
0000001F3497BB20 00007fff3d894064 ILStubClass.IL_STUB_PInvoke(IntPtr, Microsoft.UI.WindowId, IntPtr ByRef)
0000001F3497BBE0 00007fff3d893f35 ABI.Microsoft.UI.Input.IInputNonClientPointerSourceStaticsMethods.GetForWindowId(WinRT.IObjectReference, Microsoft.UI.WindowId)
0000001F3497BC30 00007fff9c576671 CollapseLauncher.MainWindow.EnableNonClientArea()
0000001F3497BC90 00007fff3d893c19 ABI.Windows.Foundation.TypedEventHandler`2[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].Do_Abi_Invoke[[System.IntPtr, System.Private.CoreLib],[System.IntPtr, System.Private.CoreLib]](Void*, IntPtr, IntPtr)
0000001F3497BD10 00007fff3d893a97 ILStubClass.IL_STUB_ReversePInvoke(Int64, Int64, Int64)
0000001F3497E498 00007fff88b6a172 [InlinedCallFrame: 0000001f3497e498] 
0000001F3497E498 00007fff9c041555 [InlinedCallFrame: 0000001f3497e498] 
0000001F3497E470 00007fff9c041555 ABI.Microsoft.UI.Xaml.IWindowMethods.Activate(WinRT.IObjectReference)
0000001F3497E540 00007fff9c576011 CollapseLauncher.MainWindow.InitializeAppWindowAndIntPtr()
0000001F3497E5B0 00007fff9c5762b3 CollapseLauncher.MainWindow.InitializeWindowSettings()
0000001F3497E630 00007fff9c575b5b CollapseLauncher.MainWindow.InitializeWindowProperties(Boolean)
0000001F3497E6C0 00007fff9c53d74c CollapseLauncher.App..ctor()
0000001F3497E750 00007fff9c62dcac CollapseLauncher.MainEntryPoint+c.b__1_0(Microsoft.UI.Xaml.ApplicationInitializationCallbackParams)
0000001F3497E790 00007fff9c02f517 ABI.Microsoft.UI.Xaml.ApplicationInitializationCallback.Do_Abi_Invoke(IntPtr, IntPtr)
0000001F3497E960 00007fff889c073a [InlinedCallFrame: 0000001f3497e960] 
0000001F3497E960 00007fff9c0372d6 [InlinedCallFrame: 0000001f3497e960] 
0000001F3497E930 00007fff9c0372d6 ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference, Microsoft.UI.Xaml.ApplicationInitializationCallback)
0000001F3497EA50 00007fff9c57419c CollapseLauncher.MainEntryPoint.Main(System.String[])
```

GetForWindowId crashes

**Comment by bagusnl** [comment]
Heyya~
Can you try this build here https://misc-r2.bagelnl.my.id/preview-debug-wasdk1.5.7z

PS. this is debug build, do not replace your collapse installation with it. Just extract all and run CollapseLauncher.exe directly

**Comment by SonicDX12** [comment]
> Heyya~ Can you try this build here https://misc-r2.bagelnl.my.id/preview-debug-wasdk1.5.7z
> 
> PS. this is debug build, do not replace your collapse installation with it. Just extract all and run CollapseLauncher.exe directly

Hi bagusnl,

Your debug build is working. No crash when I launch it. 👍

**Comment by bagusnl** [comment]
Alrighty~
Will include the fix on next update. Since you can't apply the update from the launcher itself, you have to install the new version on top of the installed one when the update dropped

Thank you for reporting this issue <3

**Comment by bagusnl** [comment]
Release with fix has been deployed, closing issue~

Thank you for letting us know about the problem!
