### ISSUE TITLE
[Request]: Preview of UI elements during custom background image cropping

### ISSUE THREAD

**Issue by Vermilion-Sinsha** [CollapseLauncher/Collapse#419]
### Is your request related to a problem?

No

### Describe your proposed solution

Collapse 1.73.4 adds the ability to crop custom background images. It would be nice to see a UI element preview feature implemented to make it easier to ensure that the waifu's face is displayed unobstructed by UI elements in this feature.

### Describe alternatives you've considered

![スクリーンショット 2024-03-06 211348](https://github.com/CollapseLauncher/Collapse/assets/131636335/72bf4605-751d-4810-80ab-59d28edf93f3)
By displaying a simple silhouette of a UI element in this way on the custom background image cropping screen, it will be easy to see how the cropped image will look.

**Comment by shatyuka** [comment]
Waiting for https://github.com/CommunityToolkit/Windows/pull/364 to get merged
