### ISSUE TITLE
[Bug]: Collapse crashes on the welcome screen

### ISSUE THREAD

**Issue by closerRen** [CollapseLauncher/Collapse#423]
### Affected Version

Collapse 1.73.5

### Bug Behavior

Crashed while reading  game list after entering the welcome screen.
[DxDiag.txt](https://github.com/CollapseLauncher/Collapse/files/14548361/DxDiag.txt)
[log-2024-03-10-sta1.73.5-id1.log](https://github.com/CollapseLauncher/Collapse/files/14548381/log-2024-03-10-sta1.73.5-id1.log)

### Expected Behavior

Collapse should have launched normally.

### Steps to reproduce

1.Launch the program.

### Screenshot(s)

![20240310093307](https://github.com/CollapseLauncher/Collapse/assets/100517599/c6fe77d1-f152-48ad-8934-6be3243a9e55)

**Comment by closerRen** [comment]
Crashes after the progress bar rotates a few times.

**Comment by bagusnl** [comment]
From the log it seems like the HTTP submodule is failing when trying to connect to our CDN. In yous system is there anything special for internet access, like proxy, VPN, firewall, etc?

**Comment by bagusnl** [comment]
@1ashari your case seems to be different from looking at the log file. Can you do these steps and submit a new ticket?


> Can you provide a crash dump?
> Try procdump -ma -i YOUR_DUMP_FOLDER, and then reproduce your crash.
> Download link here: https://download.sysinternals.com/files/Procdump.zip

**Comment by closerRen** [comment]
> From the log it seems like the HTTP submodule is failing when trying to connect to our CDN. In yous system is there anything special for internet access, like proxy, VPN, firewall, etc?

There is indeed a vpn, but whether I turn it on or off, the program crashes in the welcome screen.

**Comment by closerRen** [comment]
> From the log it seems like the HTTP submodule is failing when trying to connect to our CDN. In yous system is there anything special for internet access, like proxy, VPN, firewall, etc?

After I reconnected to your cdn, the issue has been resolved. Thank you for your help.

**Comment by bagusnl** [comment]
> There is indeed a vpn, but whether I turn it on or off, the program crashes in the welcome screen.

Since you seem to be able to open GitHub but the launcher says its failing to contact GitHub, can you check if you have firewall turned on that blocks Collapse?

For further reference "Add Program Exceptions to the Windows Firewall"
 https://supportcenter.lexisnexis.com/app/answers/answer_view/a_id/1081611/~/adding-exceptions-to-the-windows-firewall#:~:text=click%20Finish.-,Add%20Program%20Exceptions%20to%20the%20Windows%20Firewall,-Windows%208.1

**Comment by Cryotechnic** [comment]
Closing for now since OP has not replied in over 2 weeks & issue seems to be resolved.
