### ISSUE TITLE
[Known][Bug]: Random Crash on Collapse when RTSS/MSI Afterburner is installed

### ISSUE THREAD

**Issue by bagusnl** [CollapseLauncher/Collapse#431]
### Affected Version

`>= 1.73.5`

### Bug Behavior

Having Waifu2X enabled with RTSS installed **might** cause Collapse to crash unexpectedly.

A workaround without uninstalling RTSS completely is to disable RTSS Vulkan layer in registry:
1. Open regedit
2. Go to `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers`
3. On entry for `C:\Program Files (x86)\RivaTuner Statistics Server\Vulkan\RTSSVkLayer64.json` open it and change the value from 0 to 1
> Note: Doing this will disable RTSS overlay on Vulkan enabled games!

The issue is still under investigation

**Comment by shatyuka** [comment]
TODO: handle console exit to do some dispose works
