### ISSUE TITLE
[Bug]: Game + Region Change doesn't work sometimes

### ISSUE THREAD

**Issue by tcyrus** [CollapseLauncher/Collapse#435]
### Affected Version

1.73.6

### Bug Behavior

Game + Region drop-down not working after selecting "Daily Check-in" from "Community Tools"

### Expected Behavior

Game + Region drop-down should work after selecting "Daily Check-in" from "Community Tools"

### Steps to reproduce

1. Click "Community Tools"
2. Click "Daily Check-in"
3. Close the Collapse Web Browser Window
4. Try using Game or Region Drop-Down (doesn't work)

### Additional Information

Let me know if this issue cannot be reproduced

**Comment by gablm** [comment]
Hi, thanks for the bug report!
A fix for this issue should be shipped in the next version. (fb6c01d)

Some workarounds for the time being (without restarting Collapse) are:
- Change regions using keyboard shortcuts
- Change window size or language in the Settings page
After doing any of these actions, the drop-down should update and be usable again.

Sorry for the inconvenience!
