### ISSUE TITLE
[Bug]: if you have some files downloaded already, it wont let you continue if the free space is lower than required space

### ISSUE THREAD

**Issue by anispwyn** [CollapseLauncher/Collapse#445]
### Affected Version

360222b

### Bug Behavior

when you have some of the game files downloaded, you pause and then when you decide to continue, it wont let you continue if your free space is lower than required space

### Expected Behavior

it (collapse) count the downloaded files and then make the required disk space lower so it can continue

### Steps to reproduce

1. make ur drive almost full, but enough to download 1 game
2. download the game, wait until the disk space is lower than required space
3. when your free space is lower than required space, pause and continue
4. the popups appear

### Screenshot(s)

![image](https://github.com/CollapseLauncher/Collapse/assets/36318840/b1f28b0e-ea03-4d4f-89cc-b5ce5f527c90)

**Comment by bagusnl** [comment]
Func InstallManagerBase.CheckDriveFreeSpace
https://github.com/CollapseLauncher/Collapse/blob/360222ba76efe96bf75e38c186f5746ffa48f862/CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs#L1800-L1821

Unsure what's wrong with it... My sleepy brain tells something about segments calculation in segmented package (eg Genshin install packages) is not working correctly

Cc @neon-nyan

**Comment by Cryotechnic** [comment]
Issue should be addressed in a058090. You can download the build artifact [here](https://nightly.link/CollapseLauncher/Collapse/actions/runs/9232634856) and let us know if you still have the issue.
