### ISSUE TITLE
[Bug]: If Collapse updates while game is running, playtime counter does not restart after update.

### ISSUE THREAD

**Issue by Kiki79250CoC** [CollapseLauncher/Collapse#446]
### Affected Version

1.73.8

### Bug Behavior

I noticed that Collapse updated itself to the latest version while game was running, and after update, the playtime counter does not start counting again after update completed, it stays on the value it was before the update began.

I noticed that yesterday after the (long) 10-hour session I made to complete HSR 2.1 quest to avoid getting spoiled that the counter stopped counting after only 31 minutes.

### Expected Behavior

2 solutions:
  1. Collapse should temporarily pause update check if a game is running
  2. After an update, the counter should start again to count

In both case the counter should not be paused, or can be paused during update and restart immediately after.

### Steps to reproduce

1. Run game
2. *MIRACLE!* An update is detected while game is running.
3. See after update completes, the "Game is running" button is grayed out as it should be, but the playtime counter does not restart.

### Additional Information

OS : Windows 11 22H2 (10.0.22621.3296 - March 2024 MCR)

**Comment by bagusnl** [comment]
Fixed in  https://github.com/CollapseLauncher/Collapse/commit/8113ffc32f92576a720dce3e8c3306effd361bff
Fix will be shipped once #434 is merged and pushed to release

Thank you for reporting the issue!
You can keep this thread open as it will close once merge is complete

**Comment by bagusnl** [comment]
@all-contributors please add @Kiki79250CoC for translation and bug
