### ISSUE TITLE
[Request]: Launch Argument for Collapse

### ISSUE THREAD

**Issue by Mylloon** [CollapseLauncher/Collapse#454]
### Is your request related to a problem?

No

### Describe your proposed solution

Having something like `/Genshin` argument when starting Collapse, and it will directly load the "Genshin Impact" screen

### Describe alternatives you've considered

I don't know any alternatives

**Comment by gablm** [comment]
Hello!

Collapse already has a command-line argument which lets you load a specific game/region on launch.
Its syntax is the following:
```
CollapseLauncher.exe open -g <game name/id>
```

While specifying a game is required, you can also optionally:
- choose what region to load by adding
```-r <region name/id>```
If no region is specified, the last used region will be loaded.

- start the game automatically after loading the region by adding
```-p```

Note that if the game/region name has spaces, the name must be enclosed by quotes.
If you need any help or have any doubts about the usage of this argument, don't hesitate to ask!

**Comment by Mylloon** [comment]
Thanks, I didn't know that! Do you know where I can find the list of ID for the games and region?

**Comment by gablm** [comment]
The "id"s follow the order the game/region appears in the launcher selector (starting at 0).

For example:
**Games:** 0 -> HI3, 1 -> GI, 2 -> HSR
**Regions for Genshin Impact:** 0 -> Global, 1 -> Mainland China, 2 -> Bilibili

**Comment by Mylloon** [comment]
Thanks!
