### ISSUE TITLE
Reinstalling when i resume the installation on extract phase

### ISSUE THREAD

**Issue by justhar** [CollapseLauncher/Collapse#459]
### Affected Version

1.71.13

### Bug Behavior

basically, i was resuming the installation when it was on the extracting phase, but then the installer just reinstall the game 

### Expected Behavior

i guess it should continue extracting the files (?)

### Steps to reproduce

1. Pause the installation when its on extracting phase
2. continue the installation

**Comment by kleqing** [comment]
Hi. Have you tried remove the game folder installation and then create a new one, then locate the game you want to install to that folder. If it didn't work, you can try to reinstall the launcher again!

**Comment by justhar** [comment]
> Hi. Have you tried remove the game folder installation and then create a new one, then locate the game you want to install to that folder. If it didn't work, you can try to reinstall the launcher again!

ok its working now! thanks
