### ISSUE TITLE
[Bug]: Collapse Crashes when trying to Repair

### ISSUE THREAD

**Issue by IRedDragonICY** [CollapseLauncher/Collapse#461]
### Affected Version

1.80.3 Preview [Codename: TBA]

### Bug Behavior

after trying downlod missing files, it crash

### Expected Behavior

repair the file game, last preview this feature  working properly

### Steps to reproduce

1.goto Genshin Impact game repair menu
2.Quick Check
3.trying fix and crash

### Additional Information

[log-2024-05-08-pre1.80.3-id0.log](https://github.com/CollapseLauncher/Collapse/files/15243287/log-2024-05-08-pre1.80.3-id0.log)

**Comment by bagusnl** [comment]
Hi, thank you for telling us the issue, we have found a bug with the TimeSpan and @gablm already put the commit that would fix it. The fix should be pushed to release later today

https://github.com/CollapseLauncher/Collapse/issues/461

**Comment by bagusnl** [comment]
Hi, I have compiled version with fix and you can use it below. Just extract and run it to do repair on games you need to. Do not replace your current Collapse installation with this

https://www.mediafire.com/file/tgn2omq0h8vs8eb/1.80.3-timespanfix-donotreplace.7z/file

**Comment by IRedDragonICY** [comment]
Thanks for inform
