### ISSUE TITLE
[Request]: Update notice regarding 120 FPS for Star Rail

### ISSUE THREAD

**Issue by BobbyWibowo** [CollapseLauncher/Collapse#468]
### Is your request related to a problem?

No

### Describe your proposed solution

<img width="1280" alt="ShareX_StarRail_20240521-074402" src="https://github.com/CollapseLauncher/Collapse/assets/9364930/d5750aaa-4d6b-499d-ab33-13187fec1d68">

In short, Graphics Settings menu no longer breaks when using 120 FPS via registry edit. It will just display the option as 30 FPS.

Changing other graphic options also will NOT reset FPS back to 60 or lower. It will only reset when you actually change the FPS option itself.

Everything else works fine, including pressing Esc on keyboard to exit the settings menu, as if nothing breaks really.

### Describe alternatives you've considered

N/A

### Additional context

It looks like this was already noticed [since v2.1 update](https://www.pcgamingwiki.com/wiki/Topic:Y1sqgbg9ux5rdt7s), but I only found out today. Graphics Settings menu being inaccessible was too annoying for me, so I just coped with 60 FPS, hence why I never noticed.

**Comment by Cryotechnic** [comment]
Heyo, the text was updated in 696b735. This should be pushed in the next release of Collapse Preview. Thanks for your report!

**Comment by bagusnl** [comment]
An update that include this fix already been published on 1.80.5, we'll close this issue ticket.
If you have any problem, don't hesitate to reopen this or make a new ticket.

Thank you for using Collapse Launcher <3
