### ISSUE TITLE
[Bug]: Honkai Impact 3 Preload not being detected

### ISSUE THREAD

**Issue by Caelum008** [CollapseLauncher/Collapse#472]
### Affected Version

1.80.6-Pre

### Bug Behavior

HI3 Preload is now up according to the [Twitter post](https://twitter.com/HonkaiImpact3rd/status/1797553815291363721) but the launcher isn't detecting it. When I installed the official launcher, it's there so I downloaded it but the launcher still didn't detect the downloaded preload and whenever I would try to repair it, BlockMeta would appear no matter how many times I repair it.

### Expected Behavior

Collapse Launcher should've detected the preload. And BlockMeta should've been fixed and not persistently appearing whenever I try to repair.

### Steps to reproduce

1. Updated cache
2. Repair file
3. Reboot PC

### Screenshot(s)

![2024-06-03 18 42 55](https://github.com/CollapseLauncher/Collapse/assets/148611437/4ef1ab52-6456-4a89-8a43-906e660b8537)
![2024-06-03 18 42 38](https://github.com/CollapseLauncher/Collapse/assets/148611437/3ff9b5ed-e51f-4753-92b9-1922fdac15b5)
![2024-06-03 18 47 29](https://github.com/CollapseLauncher/Collapse/assets/148611437/8cc178f6-013f-41c7-8c49-358da427f88d)

**Comment by Caelum008** [comment]
Issue has been fixed. But the "Block" and "BlockMeta" still exist in the repair function no matter how many times I repair it even after the update. Nevertheless, thank you!

**Comment by bagusnl** [comment]
Thank you for the confirmation, the Block and BlockMeta keep reappearing is expected at the moment and workaround is still in the lookup.

**Comment by Cryotechnic** [comment]
Closing as GitHub should have closed this but it didn't
