### ISSUE TITLE
[Request]: Support for other Google Play version

### ISSUE THREAD

**Issue by HRTK92** [CollapseLauncher/Collapse#474]
### Is your request related to a problem?

No

### Describe your proposed solution

https://github.com/CollapseLauncher/Collapse/pull/24

Google Play version of “崩壊3rd” is supported, but the Google Play version of “原神” are not supported.

I would like it to be available for download from Collapse!

### Describe alternatives you've considered

N/A

**Comment by bagusnl** [comment]
Heya~ 

Can you send links to those regions on where to download the launchers for?

**Comment by HRTK92** [comment]
I'm sorry.
I made some mistakes in my proposal.

Here is the link to download Hara Shen from Google Play
https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact&hl=ja

**Comment by HRTK92** [comment]
アップロードしました！
https://gofile.io/d/g2waqG

**Comment by bagusnl** [comment]
![image](https://github.com/CollapseLauncher/Collapse/assets/28079733/6c3ac8e6-da0a-4315-8e74-67e0c5b1cc39)

Files are completely identical. Are you sure you can't add your installation to Collapse by doing `Locate Game` ?
If you can't, please send the app.info file from GenshinImpact_Data folder

**Comment by HRTK92** [comment]
Sorry, my mistake.
I take the liberty of closing the issue.

**Comment by bagusnl** [comment]
No worries.
Thanks for using Collapse Launcher! <3
