### ISSUE TITLE
[Bug]: Playtime isn't tracked if the game is opened before the launcher opens it

### ISSUE THREAD

**Issue by SupDos** [CollapseLauncher/Collapse#476]
### Affected Version

Collapse 1.80.8-Pre

### Bug Behavior

Playtime doesn't get recorded correctly if the Pre-Launch Commands starts the game before the launcher does after clicking "Start Game"

### Expected Behavior

Game time should be recorded correctly

### Steps to reproduce

As an example, I created a simple batch file which opens the game, and added it to the Pre-Launch commands, like so

![image](https://github.com/CollapseLauncher/Collapse/assets/6813986/cb7948e6-f386-4080-bc37-5ff60b10d9c0)
(I added a large game launch delay here just to make the issue more clear, but it can still happen with a lower delay, or even no delay at all)

The batch file contains this:

```batch
cd /d D:\Games\Genshin Impact
start "" "GenshinImpact.exe"
```

When pressing Start Game, the button changes to "Game is running", but only adds 1 second of playtime once the launcher actually launches the game itself, which I'm assuming is due to the process closing as the game is already open

```
[Warn]    Using Pre-launch command : "D:\Games\startgame.bat"
Game launch is delayed by 8000 ms
        BY USING THIS, NO SUPPORT IS PROVIDED IF SOMETHING HAPPENED TO YOUR ACCOUNT, GAME, OR SYSTEM!
[GLC]     C:\Program Files\Collapse Launcher\app-1.80.8>cd /d D:\Games\Genshin Impact
[GLC]     D:\Games\Genshin Impact>start "" "GenshinImpact.exe"
[Info]    [HomePage::StartGame()] Running game with parameters:
-screen-width 1440 -screen-height 900
[Schm]    Are Game logs getting saved to Collapse logs: False
[Warn]    ================================================ GAME STARTED ================================================
[Game]    <RI> Initializing input.
[Game]
[Game]    <RI> Input initialized.
[Game]
[Game]    Set new unhandled exception filter 00007FFBCE11D020 to replace 000000000040FE80
[Game]    <RI> Initialized touch support.
[Game]
[Info]    Added 1s [0h 0m 1s] to GIGlb playtime.
[Game]    UnloadTime: 0.672100 ms
[Game]    [2024-06-06 07:08:36.664] Genshin Start Log: GameManager Awake - NowTimeStamp:1717632516
[Game]    [2024-06-06 07:08:37.169] Genshin Start Log: GameManager Start - NowTimeStamp:1717632517
[Game]    [2024-06-06 07:08:37.169] Genshin Start Log: GameManager InitGame - NowTimeStamp:1717632517
```

The [Game] logs only start appearing once the delay has finished and the launcher "starts" the game as well.

### Screenshot(s)

Recording showing first launching the game normally, showing time being tracked correctly, then launching the game with the pre-launch command batch file, showing time tracking being wrong (launcher still says game is running here, so it still detects it correctly)

https://github.com/CollapseLauncher/Collapse/assets/6813986/6375d597-ebca-493b-b79d-53bbc6786713

### Additional Information

The launcher already seems to detect that the game is running even if it doesn't launch it itself (as the button changes to "Game is running"), so hopefully that could be what determines the playtime. Or maybe an option to only track the process, and not have the launcher launch it (that sounds weird). If this is out of scope, sorry for the trouble.

**Comment by bagusnl** [comment]
Heya!

This behavior is expected because the playtime counter requires process info to be fed from the app. Right in this line:

https://github.com/CollapseLauncher/Collapse/blob/main/CollapseLauncher%2FXAMLs%2FMainApp%2FPages%2FHomePage.xaml.cs#L1343

While it's possible to move the method to use the isGameRunning watcher, this will increase the loop overhead (should be next to negligible, but since it's a loop, it can add up).

Is there any use case on why you would want to run the game from GLC instead?

**Comment by SupDos** [comment]
Ah I see, completely understand if it's intended behaviour. Personally I run it externally as I use the fps unlocker which requires the game to be started from it, and I know it can't be added to the launcher natively as has been mentioned a few times.

I think the majority of people would never need to run the game this way anyways, so it's probably not worth moving it in the way you mentioned. I can just continue running the game externally. Thank you for the explanation!

**Comment by bagusnl** [comment]
Thank you for understanding <3
