### ISSUE TITLE
[Bug]: Preview version; Discord RPC is showing when idling, even when the option is disabled in App Settings

### ISSUE THREAD

**Issue by BobbyWibowo** [CollapseLauncher/Collapse#477]
### Affected Version

1.80.8 Preview

### Bug Behavior

N/A

### Expected Behavior

N/A

### Steps to reproduce

1. Enable "Show Discord Presence"
2. Disable "Show RPC when idling"

### Screenshot(s)

<img width="960" alt="ShareX_CollapseLauncher_20240607-132533" src="https://github.com/CollapseLauncher/Collapse/assets/9364930/8d6e7952-8710-46e2-8406-d2beae1919ea">

---

<img width="241" alt="ShareX_Vesktop_20240607-132553" src="https://github.com/CollapseLauncher/Collapse/assets/9364930/494588a4-e19a-4e14-9d3b-8d255e688869">

### Additional Information

Tried turning all the RPC-related options on/off, in case it's some kind of display mismatch with actual config values, but it didn't seem to be the case.

**Comment by shatyuka** [comment]
Get back to the home page?

**Comment by BobbyWibowo** [comment]
@shatyuka It remains

After further testing, it looks like going to App Settings kickstart the RPC instantly. When exiting App Settings, it doesn't update the RPC and just let it run with the same status of "Changing App Settings".

Additionally, starting the game, then exiting it, also won't stop RPC from still saying "In Game" with timer still running. This behavior in particular is observed even when re-launching Collapse fresh without going to App Settings.

**Comment by shatyuka** [comment]
Can not reproduce here, it seems to be a Discord latency. Do you have another device for observing Discord status?
