### ISSUE TITLE
[Bug]: error when open Collapse console 

### ISSUE THREAD

**Issue by Woody0811** [CollapseLauncher/Collapse#479]
### Affected Version

Collapse 1.73.8 and Collapse 1.80.7 Pre

### Bug Behavior

I opened it and it crashed. Even though I reinstalled it, it still shows up this error

### Expected Behavior

N/A

### Steps to reproduce

1  Collapse Launcher Installer
2 Install Collapse Launcher
3 Open 

### Screenshot(s)

![CollapseLauncher_HlJwRExN7t](https://github.com/CollapseLauncher/Collapse/assets/142097144/61e9e5db-6f1d-453a-9826-5c5b08f7745d)

### Additional Information

[DxDiag.txt](https://github.com/user-attachments/files/15746284/DxDiag.txt)
[log-2024-05-17-prevUnknown-id0.log](https://github.com/user-attachments/files/15746286/log-2024-05-17-prevUnknown-id0.log)

**Comment by neon-nyan** [comment]
Hi,
Can you try use this build and see if the error code returns non-zero value?
[canary-build-20240608.7z](https://cdn.discordapp.com/attachments/1121278963176718386/1248872618153611367/canary-build-20240608.7z?ex=66653ec3&is=6663ed43&hm=cf0d776b21c9517d17b6b0054c001a20930295e8abbde73c4a482b36876f5505&)

**Comment by Woody0811** [comment]
thank for respond
it's still this error on your build 
https://github.com/CollapseLauncher/Collapse/assets/142097144/b8a8473a-cfd1-447c-8134-cf43f238160c

**Comment by shatyuka** [comment]
Try this CI build: https://nightly.link/CollapseLauncher/Collapse/actions/runs/9437134532
and paste the error message here.

**Comment by Woody0811** [comment]
here:
FATAL ERROR ON APP MAIN() LEVEL!!!
System.ContextMarshalException: Failed to set console mode with error code: 87
at Hi3Helper.LoggerConsole.AllocateConsole()
at Hi3Helper.LoggerConsole . .ctor(String, Encoding)
at Hi3Helper.Shared.Region.LauncherConfig. InitAppPreset()
at CollapseLauncher.MainEntryPoint . Main(String[] args)

**Comment by shatyuka** [comment]
Can reproduce with `Legacy Console Mode` enabled. I'll try to fix it.

**Comment by shatyuka** [comment]
Fixed and try the latest CI build: https://nightly.link/CollapseLauncher/Collapse/actions/runs/9437786921
Note that we have no colored text support in legacy console mode.
