### ISSUE TITLE
[Request]:  a downlaod speed limiter , a donlwoad speed planifer 

### ISSUE THREAD

**Issue by zakidze** [CollapseLauncher/Collapse#480]
### Is your request related to a problem?

No

### Describe your proposed solution

i have a low internet connection i want to limite my download speed , i also want to set the speed for example 500kb/sec in the day 
and 1mb/sec at night

### Describe alternatives you've considered

no alternative

**Comment by Cryotechnic** [comment]
Hi, we've been tracking this request in #394, so feel free to check that for more info. Closing for now, thanks for your interest in the project!
