### ISSUE TITLE
[Request]:   A PLANIFIER TO CONTROL DOWNLAOD TIME

### ISSUE THREAD

**Issue by zakidze** [CollapseLauncher/Collapse#481]
### Is your request related to a problem?

No

### How is the feature request related to the problem?

no

### Describe your proposed solution

i want a planifer eg i can donwload the game only from midnight to 6 am only on weekdays

i want a planifer that controls the time of donwlaod i want to planify when the game is donwloading or updating

the downlaoder starts on its own and its stop on it own

### Describe alternatives you've considered

nothing

**Comment by zakidze** [comment]
a basic version of this would be an date time input when the donwload shold resume 
and anathor date time input when the donwload shold pause

**Comment by Cryotechnic** [comment]
Merged into #394!
