### ISSUE TITLE
[Bug]: can't switch to star rail.

### ISSUE THREAD

**Issue by SOOOOFA** [CollapseLauncher/Collapse#483]
### Affected Version

The latest.

### Bug Behavior

Eror log.
System.NullReferenceException: Object reference not set to an instance of an object.
   at CollapseLauncher.MainPage.GetLauncherEventInfo()
   at CollapseLauncher.MainPage.FetchLauncherLocalizedResources(CancellationToken Token, PresetConfigV2 Preset)
   at CollapseLauncher.MainPage.TryLoadResourceInfo(ResourceLoadingType resourceType, PresetConfigV2 preset, Boolean ShowLoadingMsg)

### Expected Behavior

The laucher should be switching to star raol without issues

### Steps to reproduce

1. start the laucher at genshin
2. switch to star rail
3. get railed

### Screenshot(s)

![изображение](https://github.com/CollapseLauncher/Collapse/assets/166280072/d4af71e1-a43b-44fa-8b69-7898e0e9e45b)

**Comment by TypicalShavonne** [comment]
im also getting that issue
`System.NullReferenceException: Object reference not set to an instance of an object.
   at CollapseLauncher.MainPage.GetLauncherEventInfo()
   at CollapseLauncher.MainPage.FetchLauncherLocalizedResources(CancellationToken Token, PresetConfigV2 Preset)
   at CollapseLauncher.MainPage.TryLoadResourceInfo(ResourceLoadingType resourceType, PresetConfigV2 preset, Boolean ShowLoadingMsg)`

**Comment by Ocrosoft** [comment]
You can download the preview version, it works.
https://github.com/CollapseLauncher/Collapse/releases/tag/CL-v1.80.8-pre

**Comment by andywondering** [comment]
I had the same issue. I can still run the game manually.

**Comment by Ocrosoft** [comment]
I guess it is cause by metadata v3, but the main branch was already removed this line:
https://github.com/CollapseLauncher/Collapse/commit/d75654d1f11e9a5d0af007625cbc8727c1158ba7

**Comment by Ocrosoft** [comment]
@neon-nyan @bagusnl
This issue was effected stable version users, maybe you'll want to look into it...

**Comment by TypicalShavonne** [comment]
im unable to switch to other branch of the project

**Comment by bagusnl** [comment]
@Cryotechnic is inn process of pushing 1.80.x branch to stable. Please wait.

In the meantime, you can either do these steps to override the current region if its stuck:

1. Launch Collapse Launxher with `oobesetup` argument to retrigger OOBE setup page. Please use same settings as last time but DONT pick the problematic game/region

2. Use launch command
Eg. `CollapseLauncher.exe -g 0 -r 0`

3. Edit the config manually to switxh from Star Rail
Go to `%AppData%/../LocalLow/Collapse Launcher/`
Open config.ini and override the current game and region selected manually or remove it altogether
