### ISSUE TITLE
[Bug]: Connection Issue but Internet is connected

### ISSUE THREAD

**Issue by cartonofmilks** [CollapseLauncher/Collapse#484]
### Affected Version

1.73.8

### Bug Behavior

System.NullReferenceException: Object reference not set to an instance of an object.
   at CollapseLauncher.MainPage.GetLauncherEventInfo()
   at CollapseLauncher.MainPage.FetchLauncherLocalizedResources(CancellationToken Token, PresetConfigV2 Preset)
   at CollapseLauncher.MainPage.TryLoadResourceInfo(ResourceLoadingType resourceType, PresetConfigV2 preset, Boolean ShowLoadingMsg)

### Expected Behavior

Launcher should just connect to the preview for launching to Honkai Star Rail. Instead sends me to "Your Internet is Disconnected" screen. Am connected to internet, various other applications are connected to the internet i.e. Steam, Arknights, Wuthering Waves

### Steps to reproduce

1. Launched Collapse Launcher
2. Launched Honkai Impact 3rd - Global from Collapse Launcher
3. Exit Honkai Impact 3rd - Global
4. Change to Honkai Star Rail - Global
5. "Your Internet is Disconnected" Screen pops up

### Screenshot(s)

![image](https://github.com/CollapseLauncher/Collapse/assets/173029295/a0346da9-1ae4-497c-a1b5-e03c606f8f40)
![image](https://github.com/CollapseLauncher/Collapse/assets/173029295/dd50e87a-c94e-4eb0-adb6-5f67854d3a7c)

**Comment by bagusnl** [comment]
@Cryotechnic is inn process of pushing 1.80.x branch to stable. Please wait.

In the meantime, you can either do these steps to override the current region if its stuck:

1. Launch Collapse Launxher with `oobesetup` argument to retrigger OOBE setup page. Please use same settings as last time but DONT pick the problematic game/region

2. Use launch command
Eg. `CollapseLauncher.exe -g 0 -r 0`

3. Edit the config manually to switxh from Star Rail
Go to `%AppData%/../LocalLow/Collapse Launcher/`
Open config.ini and override the current game and region selected manually or remove it altogether

**Comment by Cryotechnic** [comment]
Closing as this should be resolved in the latest Stable build.
