### ISSUE TITLE
[Bug]: Launcher crashing upon HSR 

### ISSUE THREAD

**Issue by TypicalShavonne** [CollapseLauncher/Collapse#485]
### Affected Version

1.73.8

### Bug Behavior

System.NullReferenceException: Object reference not set to an instance of an object. at CollapseLauncher.MainPage.GetLauncherEventInfo() at CollapseLauncher.MainPage.FetchLauncherLocalizedResources(CancellationToken Token, PresetConfigV2 Preset) at CollapseLauncher.MainPage.TryLoadResourceInfo(ResourceLoadingType resourceType, PresetConfigV2 preset, Boolean ShowLoadingMsg)

### Expected Behavior

Launcher opening like normally

### Steps to reproduce

1. Open launcher with HSR 
2. Crashed

### Related Issues

#483

**Comment by bagusnl** [comment]
@Cryotechnic is inn process of pushing 1.80.x branch to stable. Please wait.

In the meantime, you can either do these steps to override the current region if its stuck:

1. Launch Collapse Launxher with `oobesetup` argument to retrigger OOBE setup page. Please use same settings as last time but DONT pick the problematic game/region

2. Use launch command
Eg. `CollapseLauncher.exe -g 0 -r 0`

3. Edit the config manually to switxh from Star Rail
Go to `%AppData%/../LocalLow/Collapse Launcher/`
Open config.ini and override the current game and region selected manually or remove it altogether

**Comment by TypicalShavonne** [comment]
how can i switch it to preview branch ?

**Comment by Ocrosoft** [comment]
> how can i switch it to preview branch ?

Checkout to tag: CL-v1.73.8

**Comment by Cryotechnic** [comment]
Fixed in 1.80.9, thanks for the report!
