### ISSUE TITLE
[Bug]: Collapse downloaded Wrong Voice Pack Pre-load file for HSR 2.3

### ISSUE THREAD

**Issue by berryboiii09** [CollapseLauncher/Collapse#488]
### Affected Version

Collapse Launcher 1.80.9 Stable

### Bug Behavior

The Launcher have downloaded Korean Voice Pack Pre-load file for Star Rail 2.3 despite the fact I neither use Korean voice or have it Installed and It didn't download the preload files for the voice packs that I've installed (Which is English only in my case)

I verified the downloaded files in the launcher, and It said that 3 files will be verified despite It only downloaded 2 files, After verifying two files it skipped the _"third file"_ and said Verifying is successful

Then I attempted to remove the downloaded korean voice from the game folder, but unlike the first time i downloaded the files the launcher said that 3 files are to be downloaded and it still downloaded Korean files again and didn't download a third file after pressing "Download Now" in it

Today's log doesn't seem to have relevant info but here it is anyways
[log-2024-06-17-sta1.73.8-id1.log](https://github.com/user-attachments/files/15871464/log-2024-06-17-sta1.73.8-id1.log)

### Expected Behavior

The Launcher should have downloaded Game and English Voice Pre-load files for the upcoming HSR 2.3 Update. The Launcher only have done the former but not the latter and instead downloaded Korean Pre-load files only

### Steps to reproduce

1.Download the Pre-load for HSR 2.3 by presssing "Download Now" in the launcher
2.Wait until files are downloaded and verified
3.Check the game's folder

### Screenshot(s)

![Screenshot 2024-06-17 114709](https://github.com/CollapseLauncher/Collapse/assets/173062273/1706bb67-3f86-45bf-aa66-511c7398ea95)
Launcher while downloading the files for the first time
..........................
![Screenshot (313)](https://github.com/CollapseLauncher/Collapse/assets/173062273/9cce5318-7e09-4d3e-99e0-34680789584d)
The downloaded files in the game's folder
..............................
![Screenshot (314)](https://github.com/CollapseLauncher/Collapse/assets/173062273/6558601f-d4dd-4511-a27f-0ebcd8e8bd19)
The Launcher while verifying the filles (Notice how the number of files in this screenshot and first screenshot is different)
...................................
![Screenshot (315)](https://github.com/CollapseLauncher/Collapse/assets/173062273/941ece4f-63e4-4d1d-b96e-fb36a7180f69)
After I removed the Korean files and downloading missing files, It ended up redownloading Korean files again and no other files

### Additional Information

1 - I only have English voice installed
2 - Download Threads is set to 8, and Extraction Threads is 0, "Merge downloaded package chunks" is turned off
3 - Not sure if this is related to my issue but Earlier today the launcher didn't want to open and said "Your Internet is Disconnected", Something like Issue #484 , I ended fixing it by removing the config files in "AppData/LocalLow/Collapse Launcher/", After fixing it i installed the new update for the launcher by Clicking "Check for updates" in the launcher settings

**Comment by berryboiii09** [comment]
**Update**

I tried to change the Game Voice to Korean via the Launcher's Game settings tab and after I saved and went back to the home screen it asked me to Download Missing Pre-load files, I hit "Download Now" and Checked the game folder only to find that it's downloading the English Voice Pre-load files 🤣

Will try to do the same but for Japanese and Chinese Voice and see what would happen

![Screenshot (317)](https://github.com/CollapseLauncher/Collapse/assets/173062273/c83df832-450e-4bd7-ac36-d34582770c49)
![Screenshot (316)](https://github.com/CollapseLauncher/Collapse/assets/173062273/3215bb6e-c059-45a9-93a6-b4b3188d4f56)
![Screenshot (318)](https://github.com/CollapseLauncher/Collapse/assets/173062273/d811d453-9279-4b30-aeb0-1ea22d2b68db)

**Comment by neon-nyan** [comment]
Hi @berryboiii09,
Sorry for our late response due to unavailability of our team at the moment.

We just found out that the cause of the issue is because the VO packages in the API has been out of order compared to what we currently implement now.
The launcher was expecting the order to be like this:
```CSharp
0 => "zh-cn"
1 => "zh-tw"
2 => "en-us"
3 => "ja-jp"
4 => "ko-kr"
```
But we just found out that the HYP API has different order, like this:
```CSharp
0 => "zh-cn"
1 => "zh-tw"
2 => "ko-kr"
3 => "ja-jp"
4 => "en-us"
```
This causes the selection of the index No. 2 has been selectively wrong to "ko-kr", causing Korean Voice Over to be downloaded instead.
We just pushed a commit to fix this issue and we will be going to push a hotfix regarding this.

Sorry for the inconvenience

**Comment by neon-nyan** [comment]
Oops, reopen the issue

**Comment by berryboiii09** [comment]
@neon-nyan It's alright, and Thank you
I will wait for the fix

**Comment by berryboiii09** [comment]
After updating to the new hotfix version 1.80.10, The Launcher now correctly downloads and verifies the voice pre-load file for English and Korean voices, Also It no longer attempts to download or verify more files

Thank you all for your hard work 🙏
