### ISSUE TITLE
[Request]: disable auto updates

### ISSUE THREAD

**Issue by zakidze** [CollapseLauncher/Collapse#489]
### Is your request related to a problem?

Yes

### How is the feature request related to the problem?

today a new version come out 1.8 and i was in version 1.73 donwloading ginshin impact the donlwoad reached 90%
then the launcher restarted on it self , then the downlaod back to  0 i did not understand what happen until i noticed that the launcher have updated

so i backedup the donload data and reverted to old version and start donwload again everything went fine again

### Describe your proposed solution

add a button to stop auto update , also prevent the app from updating whille installing or extracting,,,,,

### Describe alternatives you've considered

.

**Comment by bagusnl** [comment]
This actually has been fixed on the 1.80.x branch by @gablm 

But the download restart is quite odd, there might be a change in the download thread count during the update (also been fixed) unnoticed so the download seemed to restart itself

**Comment by bagusnl** [comment]
Ah you meant for Genshin?

1.7x.x technically doesnt have a function to force update the launcher. So you could've set your internet as metered to force the updater to not update the launcher.

We unfortunately could not make an option to disable update entirely due to the fact that we had quite a lot of bug reports that indicated user usibg old launcher that the bug happened. Also, since hoyo games is all "live service" games, its impossible for the launcher to continue function when the launcher is not updated due to changes in API wise

**Comment by zakidze** [comment]
then why not make kind of modal thats says lancher shold be updated and give the user 24 houers before forcing update

**Comment by zakidze** [comment]
in my case i needed to finish the download🤣🤣🤣🤣🤣🤣🤣

**Comment by bagusnl** [comment]
I'll consult the other members and see what we can do about it

**Comment by bagusnl** [comment]
After thinking and discussing with other members, we don't think adding defer update feature or any way to stop a forced update is good for the user as there might be a hotfix that we really need to push that break some usage. Though the auto update will always be disabled when the launcher is downloading something and if the network is under metered (there will be a popup).

We also add a function to disable sophon using a file identifier, but we dont know how long this feature will be available knowing hoyo might disable their zip API.

Thanks for using Collapse~

**Comment by zakidze** [comment]
then if the auto update would be disabled while doing some actions than thats great, why not to include a button to stop autoupdate like for urgent only like stop for 1 day only than its gonna force update later , the button is going to be used like once in 3 days or somthing and it stops minor updates not the urgent updates 

like best of both words
