### ISSUE TITLE
[Bug]: No Cancel button on updating screen

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#490]
### Affected Version

Collapse 1.80.8 Preview, when updating to 1.80.9 Preview

### Bug Behavior

The `Cancel` button does not appear when updating Collapse.

### Expected Behavior

The `Cancel button should appear when updating Collapse.

### Steps to reproduce

1. Open 1.80.8 Preview
2. Wait for the auto-update screen to appear

### Screenshot(s)

Showing how the visual bug appears with small/large window sizes:
https://github.com/CollapseLauncher/Collapse/assets/88598340/1ecd1950-3725-466b-84af-9f2a7ab72450

### Additional Information

I believe that this has started to appear since a few preview versions ago, but I just haven't reported it until now.

[DxDiag.txt](https://github.com/user-attachments/files/15875674/DxDiag.txt)

**Comment by Cryotechnic** [comment]
Fixed in 1.80.10
