### ISSUE TITLE
[Request]: Add blur animation to the top bar and other elements.

### ISSUE THREAD

**Issue by DuckDeng** [CollapseLauncher/Collapse#494]
### Is your request related to a problem?

No

### How is the feature request related to the problem?

Skipped

### Describe your proposed solution

![image](https://github.com/CollapseLauncher/Collapse/assets/64295725/fa019290-4832-44d2-8f10-17fc7c46481d)

1. Notifiction button was placed near the Close and Maximize. Close and Maximize are linear and non-background icons, but Notifiction icon with a white background. Can their display styles be unified?

2. The black icons in the sidebar are not clear against a dark background(like the green mark on image). 

### Describe alternatives you've considered

This is a UI design issue and doesn't require an alternative solution to instead.

### Additional context

None

**Comment by bagusnl** [comment]
The dark icon might have been forgotten during our removal of left bar (addition of auto transparent left bar) so the UI button in light mode is a bit occluded/hard to see on certain background.

@shatyuka can you help me on this one? I'm still confused myself reading the main app theme xamls

**Comment by bagusnl** [comment]
@neon-nyan has mitigated this in Preview branch release.
Reopen this ticket if you think there still needs improvements to this issue~

## Dark Mode
### Light Background
![image](https://github.com/user-attachments/assets/c14b1fb9-f51c-4cbf-9d15-0bc8e3a47ac0)

### Dark Background (Background credit: Shuno on Pixiv https://www.pixiv.net/en/artworks/100895729)
![image](https://github.com/user-attachments/assets/24f982ed-7811-4a25-8b61-1399d1fb4568)

## Light Mode
### Light Background
![image](https://github.com/user-attachments/assets/c09ca3ae-2192-4dbc-88c1-8b213246d2f5)


### Dark Background (Background credit: Shuno on Pixiv https://www.pixiv.net/en/artworks/100895729)
![image](https://github.com/user-attachments/assets/27db74ed-9e96-4795-8929-05110aafc418)

Thank you for your support <3
