### ISSUE TITLE
[Bug]: program is not opening

### ISSUE THREAD

**Issue by AphelG7** [CollapseLauncher/Collapse#495]
### Affected Version

1.18.10

### Bug Behavior

When running the program it opens and closes then

### Expected Behavior

open normally

### Steps to reproduce

just run the exe

### Additional Information

[DxDiag.txt](https://github.com/user-attachments/files/15890070/DxDiag.txt)

(dont have the log file, idk why)

**Comment by AphelG7** [comment]
I deleted an old log folder (August 2023) and Launcher opened normally again

**Comment by AphelG7** [comment]
bugged again
[log-2024-06-18-sta1.80.10-id0.log](https://github.com/user-attachments/files/15890800/log-2024-06-18-sta1.80.10-id0.log)

**Comment by bagusnl** [comment]
> bugged again [log-2024-06-18-sta1.80.10-id0.log](https://github.com/user-attachments/files/15890800/log-2024-06-18-sta1.80.10-id0.log)

please update to .11 and try again

**Comment by AphelG7** [comment]
![image](https://github.com/CollapseLauncher/Collapse/assets/24282872/f7fb8b9a-91f0-4f1a-85fe-6132b0c31274)
nice, thank you for help
