### ISSUE TITLE
[Request]: Option to choose between "Sophon Chunk download method" and " Direct zip files download method"

### ISSUE THREAD

**Issue by VoidDarkness01** [CollapseLauncher/Collapse#498]
### Is your request related to a problem?

No

### Describe your proposed solution

Please add an option in *Collapse* launcher settings with which we can choose between the game version update and game fresh install download method. Mainly between "Sophon Chunk download method" and the direct zip files download method. 

### Describe alternatives you've considered

The previous stable version of collapse launcher had the zip file direct download method.

**Comment by bagusnl** [comment]
Heya! Currently chunk download system only available for Genshin. Is there any advantage of why you want the zip download method instead of chunk?

**Comment by Cryotechnic** [comment]
While I'm not going to explicitly say "no", this would greatly depend on HoYoVerse to continue providing a valid API route for us to be able to continue supporting the direct ZIP download method. 

With how things are looking, it looks like they are transitioning away from ZIP DDL to a chunk-based Sophon implementation on their new HoYoPlay launcher. This would mean that, over time and eventually, when all their games & their respective regions are migrated to the new launcher, the ZIP download method will be completely deprecated.

I'm also confused as to why you'd want a direct ZIP file download, as Sophon is not only more efficient in terms of bandwidth used, but also requires much less storage on the drive.

Again, not saying "no", but highly unlikely unless they decide to keep the ZIP files on their API.

**Comment by VoidDarkness01** [comment]
Hello, thanks for replying. The reason i want the zip files direct download
method is because i manually download the *game* version update file from
links posted on Reddit as it is more convenient for me. Here's the link to
latest HSR version 2.3 :
https://www.reddit.com/user/RhiskOMG/comments/1di273o/direct_download_links_for_honkai_star_rail_23/

**Comment by VoidDarkness01** [comment]
Hello, thanks for replying, i agree with you. The reason i want the zip
files direct download method is because i manually download the *game*
version update file from links posted on Reddit as it is more convenient
for me. Here's the link to latest HSR version 2.3 :
https://www.reddit.com/user/RhiskOMG/comments/1di273o/direct_download_links_for_honkai_star_rail_23/
And then i paste the downloaded file into the location where the zip file
is originally downloaded by the launcher. So then i open up the launcher
and the launcher recognize it and verify and updates the game. With sophon
chunk implemented in the launcher, this manual version update file download
method no longer works because the launcher does not recognize the
downloaded file and even if it does and updates the game, after game
verification, it again starts download a whole 30 gb update.
