### ISSUE TITLE
[Request]: Add switch for old logo

### ISSUE THREAD

**Issue by sino1641** [CollapseLauncher/Collapse#506]
### Is your request related to a problem?

No

### Describe your proposed solution

I notice the collapse logo is changed to another new energetic one, but I still prefer if there is a way to keep the old yellow/blue logo.
It could be better if there is a switch in settings to allow users using old or new logos per their preferrences.

### Describe alternatives you've considered

Maybe the software can read a custom png/svg file in data folder instead of hard coding.
(I am not professional in Software Development so I don't know whether this optoion would be easier or much more difficult.)

**Comment by bagusnl** [comment]
After discussing with neon, we are not going to implement any changes in our Logo mechanism as we want to establish brand. The new logo will be our Launcher logo and the old one will be our organization logo (also other published packages such as SharpHDiffPatch, Sophon, etc)

Thank you for your support <3
