### ISSUE TITLE
[Bug]: Some bugs with updating Genshin Impact

### ISSUE THREAD

**Issue by MicGan6** [CollapseLauncher/Collapse#515]
### Affected Version

Collaspe 1.80.14

### Bug Behavior

When I try to update Genshin Impact, it tunred into Sophon Mode, and it begun to download files, it's over 70GB! But the normal size is 24GB. I've download the game before

### Expected Behavior

Begin to download the file normaly, not sophon mode. And the size of the file is about 24GB

### Steps to reproduce

1. I opened the launcher
2. I hited the update button
3. It begins to download a 70GB file

### Screenshot(s)

![image](https://github.com/CollapseLauncher/Collapse/assets/142008387/d96c5e30-0633-4e7f-8e5f-f7290477a896)

**Comment by bagusnl** [comment]
on the game directory can you do this command with cmd?
```tree /F /A >basegame_gi[your region].txt```
then upload the file here

Also look at the config.ini in base game folder and the app.info file inside [GenshinImpact/YuanShen]_Data/ folder, you can either just copy the content here or upload the file

**Comment by GanGan1** [comment]
> on the game directory can you do this command with cmd? `tree /F /A >basegame_gi[your region].txt` then upload the file here
> 
> Also look at the config.ini in base game folder and the app.info file inside [GenshinImpact/YuanShen]_Data/ folder, you can either just copy the content here or upload the file

Sorry that the language of my System is Chinese

**Comment by GanGan1** [comment]
> on the game directory can you do this command with cmd? `tree /F /A >basegame_gi[your region].txt`然后在此处上传文件
> 
> Also look at the config.ini in base game folder and the app.info file inside [GenshinImpact/YuanShen]_Data/ folder, you can either just copy the content here or upload the file

Sorrt but I can't understand that how to do this. I mean that input what to replace '[your region]'

**Comment by bagusnl** [comment]
oh, just put cn or glb if the game is either mainland china region or global
it doesn't really matter

**Comment by GanGan1** [comment]
> oh, just put cn or glb if the game is either mainland china region or global it doesn't really matter

Sorry but here came an error, My system is Chinese language, so maybe you should translete it
out-file : 无法执行操作，因为通配符路径 basegame_gi[global].txt 无法解析为文件。
所在位置 行:1 字符: 1
+ tree /F /A >basegame_gi[global].txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (basegame_gi[global].txt:String) [Out-File], FileNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

**Comment by bagusnl** [comment]
Oh, dont use Powershell, use Command prompt

**Comment by GanGan1** [comment]
> Oh, dont use Powershell, use Command prompt

emmm, cmd have somethnig wrong with cd command, I can;t use it, it doesn't work...
My system is Win10

**Comment by bagusnl** [comment]
huh, its fine then, just send me the contents of the `config.ini` and `YuanShen_Data/app.info` file to here

**Comment by GanGan1** [comment]
--------------------------config.ini--------------------------------
[General]
channel=1
sub_channel=0
cps=
game_version=4.6.0
sdk_version=
uapc={"hk4e_global":{"uapc":""},"hyp":{"uapc":""}}

**Comment by GanGan1** [comment]
--------------------------------app.info-------------------------------------
miHoYo
Genshin Impact

**Comment by GanGan1** [comment]
> huh, its fine then, just send me the contents of the `config.ini` and `YuanShen_Data/app.info` file to here

above this comment is the information in those files

**Comment by bagusnl** [comment]
Ah alright, so its Global region
we'll investigate what happened but for now, can you make an empty file next to `GenshinImpact.exe` called `@DisableSophon` then relaunch the launcher and try to update again

**Comment by GanGan1** [comment]
> Ah alright, so its Global region we'll investigate what happened but for now, can you make an empty file next to `GenshinImpact.exe` called `@DisableSophon` then relaunch the launcher and try to update again

Thank you. I'll try it

**Comment by GanGan1** [comment]
> Ah alright, so its Global region we'll investigate what happened but for now, can you make an empty file next to `GenshinImpact.exe` called `@DisableSophon` then relaunch the launcher and try to update again

Thank you a lot. It works.

**Comment by bagusnl** [comment]
We'll reopen this issue for now as the Sophon method is apparently still broken, the `@DisableSophon` file will disable the chunk update method and use old zip method instead (we don't know how long they will still zip updates/packages), so fixing the new method is preferable

CC @neon-nyan

**Comment by bagusnl** [comment]
Fixed both in Stable and Preview
If you still have problem, reopen this ticket or open another one.

Thanks for the support <3
