### ISSUE TITLE
[Request]:  force update only if the game its in my list

### ISSUE THREAD

**Issue by zakidze** [CollapseLauncher/Collapse#517]
### Is your request related to a problem?

No

### Describe your proposed solution

say i only play ginshin impact and you guys noticed a problm about honkay impact and desicded to fix a bug urgently

for honkay impact ,,,,, i would like to recive the update later bcause i m not in rush like not each time i come to play ginshin i find the launcher get updates

### Describe alternatives you've considered

......

**Comment by Cryotechnic** [comment]
No. See #489 . Also, please stop trying to circumvent issues when we close them by opening issues that are similar and nigh-identical. Thanks! :)
