### ISSUE TITLE
[Bug]: Zenless zone zero launches to an endless gray screen 

### ISSUE THREAD

**Issue by ms1021** [CollapseLauncher/Collapse#522]
### Affected Version

1.80.14

### Bug Behavior

When I launch ZZZ through collapse launcher it doesn't launch properly, stuck on gray screen with no sound

### Expected Behavior

It should have launched the game

### Steps to reproduce

1. Open Collapse Launcher
2. Change the game to ZZZ
3. Press Start Game

### Screenshot(s)

![image](https://github.com/CollapseLauncher/Collapse/assets/32498333/289fadb4-6423-486e-a6cd-ac116e441667)
[DxDiag.txt](https://github.com/user-attachments/files/16101908/DxDiag.txt)

**Comment by bagusnl** [comment]
Try to reinstall your graphics driver with DDU

**Comment by ms1021** [comment]
> Try to reinstall your graphics driver with DDU

Done sadly still the same problem, not sure if I specified but it only happens when launching through collapse launcher. It launches fine through hoyoplay

**Comment by ms1021** [comment]
Turns out the Collapse Launcher made it's own directory for ZZZ instead of using the one from HoyoPlay so all I had to do is delete that and Locate the hoyo install location
