### ISSUE TITLE
[Bug]: Zenless Zone Zero shortcut does not work

### ISSUE THREAD

**Issue by TypicalShavonne** [CollapseLauncher/Collapse#524]
### Affected Version

1.80.14 Stable

### Bug Behavior

The game ZZZ does not launching upon clicking the shortcut

### Expected Behavior

ZZZ Game launched

### Steps to reproduce

1. Open Collapse Launcher
2. Create ZZZ game shortcut
3. Open the game shortcut

### Screenshot(s)

When clicking the game shortcut, it take me to this screen 
![image](https://github.com/CollapseLauncher/Collapse/assets/53472591/772fb464-cd21-4a5a-a28f-5c104c691fcc)
but not starting the game

**Comment by bagusnl** [comment]
![image](https://github.com/CollapseLauncher/Collapse/assets/28079733/18a90764-a8b3-4286-b495-79cff732b815)

make sure you check the box to make it automatically run the game

**Comment by TypicalShavonne** [comment]
that works now, thanks, forgot to tick that when i created the shortcut
