### ISSUE TITLE
[Bug]: Collapse does not continue extraction when cancelled

### ISSUE THREAD

**Issue by NSPC911** [CollapseLauncher/Collapse#525]
### Affected Version

Collapse 1.80.12 Stable (Portable)

### Bug Behavior

Wanted to install Zenless Zone Zero.
- It downloaded the 50GB of resources
- It verified the resources and started extracting.
- I cancelled the extraction (don't remember why)
- After a while, I pressed the <kbd>Install/Locate Game</kbd> button
- It asked where to download, I pressed <kbd>Use default directory</kbd>
- It turned the <kbd>Install/Locate Game</kbd> to <kbd>Launch Game</kbd>
- Attempts to launch the game results in a crash, with the Segmented Archives remaining in the `ZenlessZone Zero Game` Folder

### Expected Behavior

Collapse should have detected the segmented archives and re-started extraction

### Steps to reproduce

1. Go through the Download process and Verification process
2. While extracting, cancel it (can be through force-stop or just <kbd>Pause/Cancel</kbd>
3. Press <kbd>Install/Locate Game</kbd> again

### Additional Information

I have a couple `.dmp` logs in `C:\Users\%USERNAME%\AppData\Local\Temp\miHoYo\ZenlessZoneZero\Crashes`, but WinDbg doesn't really show anything in it.
Replaced my username with %USERNAME% because it is a bit personal
[Player.log](https://github.com/user-attachments/files/16114890/Player.log)

**Comment by bagusnl** [comment]
Hi, recently hoyo pushed an update for zzz to ver 1.0.1, that is why its asking for a redownload.
I have made a workaround for it. However, due to the complexity of it, please join our Discord server to get it so I can guide you faster if something goes wrong.

**Comment by NSPC911** [comment]
> Hi, recently hoyo pushed an update for zzz to ver 1.0.1, that is why its asking for a redownload.

- It doesn't ask to redownload, it doesn't even download it. 
- I tried the steps again and I still face the issue. Honkai: Star Rail also faces this issue (not sure about others)

**Comment by bagusnl** [comment]
Does this still happen with latest ver (1.80.15) ?

**Comment by NSPC911** [comment]
haven't tested it yet

**Comment by bagusnl** [comment]
Stale ticket, let us know if you still have this problem
