### ISSUE TITLE
[Bug]: Error when opening Genshin Impact settings

### ISSUE THREAD

**Issue by BitingHalberd** [CollapseLauncher/Collapse#527]
### Affected Version

Collapse 1.80.14/Genshin Impact 4.7

### Bug Behavior

Opening the settings for Genshin Impact in Collapse throws this error:

I followed the advice in the error and it did not help.

I do not have a "_logs" folder for some reason

`System.Exception: Failed when reading game settings GENERAL_DATA_h2389025596!
Fallback default value is used.

Unless you have never opened the game (fresh installation), please open the game and change any settings, then safely close the game. If the problem persist, report the issue on our GitHub

System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, Cannot find registry key GENERAL_DATA_h2389025596
   at CollapseLauncher.GameSettings.Genshin.GeneralData.Load()
 ---> System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, Cannot find registry key GENERAL_DATA_h2389025596
   at CollapseLauncher.GameSettings.Genshin.GeneralData.Load()
   Exception_EndOfInnerExceptionStack`
[log-2024-07-07-sta1.80.14-id1.log](https://github.com/user-attachments/files/16122522/log-2024-07-07-sta1.80.14-id1.log)
[log-2024-07-07-stavUnknown-id1.log](https://github.com/user-attachments/files/16122523/log-2024-07-07-stavUnknown-id1.log)

### Expected Behavior

It should not error

### Steps to reproduce

1: Open Collapse 
2: Open game settings for Genshin Impact

**Comment by bagusnl** [comment]
This has been fixed in the main branch, I'll push a hotfix for this later today (most likely last hotfix for this minor patch for preview as we move to next experimental stuff)

**Comment by bagusnl** [comment]
Close as fix has been pushed
