### ISSUE TITLE
[Bug]: Preload isn't downloading

### ISSUE THREAD

**Issue by Caelum008** [CollapseLauncher/Collapse#535]
### Affected Version

1.80.15-Pre

### Bug Behavior

The preload isn't downloading. It's showing to download the preload but when I finish downloading, it goes back to Preload package available.

### Expected Behavior

Should finish downloading and say Verify instead of back to Download Now.

### Steps to reproduce

1. Updated the metadata
2. Cleared the metadata and restarted
3. Tried redownloading the preload..

### Related Issues

#534

### Screenshot(s)

https://github.com/user-attachments/assets/dfb062e6-06f3-4d00-adbe-8dda0e0ea665

**Comment by bagusnl** [comment]
Known bug, fixed by @neon-nyan in https://github.com/CollapseLauncher/Collapse/commit/2737288893c67e0f1b1f1f0d1431399a91aa04ec

**Comment by bagusnl** [comment]
Fixed both in Stable and Preview
If you still have problem, reopen this ticket or open another one.

Thanks for the support <3
