### ISSUE TITLE
[Bug]: Collapse crashes while downloading the latest pre-load package for Genshin Impact

### ISSUE THREAD

**Issue by TheInternetUse7** [CollapseLauncher/Collapse#536]
### Affected Version

Collapse 1.80.15 Stable

### Bug Behavior

When I try to download the pre-load package for v4.8.0 Genshin Impact, it would download for few seconds and the app becomes unresponsive then immediately crashes.
Other functions of the app work as expected with no problem.

I found two Error level logs in the windows Event Viewer:

```
Log Name:      Application
Source:        .NET Runtime
Date:          
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      
Description:
Application: CollapseLauncher.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException: Arg_IndexOutOfRangeException
   at System.IO.StreamWriter.WriteLine(String)
   at Hi3Helper.LoggerBase.WriteLog(String, LogType)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```
```
Log Name:      Application
Source:        Application Error
Date:          
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:         
Computer:      
Description:
Faulting application name: CollapseLauncher.exe, version: 1.80.15.0, time stamp: 0x66470000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3880, time stamp: 0xdb9989e8
Exception code: 0xe0434352
Fault offset: 0x000000000005fabc
Faulting process id: 0x0x2A10
Faulting application start time: 0x0x1DAD6D11C355EBD
Faulting application path: C:\Program Files\Collapse Launcher\app-1.80.15\CollapseLauncher.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 814b56b1-e23e-47e9-8630-26fb833b8ae4
Faulting package full name: 
Faulting package-relative application ID: 
```
These are all the details I am willing to provide.

I tried updating .NET and ran `sfc /scannow` and `DISM /Online /Cleanup-Image /RestoreHealth`. The issue continues.

### Expected Behavior

The app should download the pre-load package.

### Steps to reproduce

1. Open the app
2. Switch the game to Genshin Impact if not already selected
3. Start the download for pre-load package for v4.8.0
4. Wait few seconds to watch the app crash

**Comment by bagusnl** [comment]
Try go to settings then clear the log files then run again. If it still crashes, send us the log file.
Go to settings, open `_logs` folder, and send us the latest file

**Comment by TheInternetUse7** [comment]
The problem is gone after getting the update for version 1.80.16 and clearing the logs.

**Comment by bagusnl** [comment]
Thanks for letting us know. There were some fixes for logger function so it might be that one.
Closing this issue~
