### ISSUE TITLE
[Bug]: Download speed is not accurate

### ISSUE THREAD

**Issue by Gaojianli** [CollapseLauncher/Collapse#540]
### Affected Version

1.80.16

### Bug Behavior

The download speed is much larger than my physical link limit (1 Gbps）.
Also, the network speed in task manager is smaller than the one in the collapse
![image](https://github.com/user-attachments/assets/a03ee7a9-42dc-4a9e-93e9-ae589f559966)

### Expected Behavior

The speed shows correctly.

### Steps to reproduce

1. Open the app
2. Click the "Update" button

### Screenshot(s)

![image](https://github.com/user-attachments/assets/3e1bf0df-07ba-4369-be82-154e8adabef8)

**Comment by shatyuka** [comment]
https://discord.com/channels/1116150300324139131/1116167336953647105/1263028279850307615

### Regarding Genshin Preload/Update says Downloading
Hi Travelers! 
You might notice when you are applying the preload or updating to current patch its says Downloading.It's not! There is a bug in the UI that makes it that way, we'll be fixing that for the next patch. 
In the meantime let it run and you shouldn't download more than 12GB for 1 voice lang (add about 3GB for each more).

Also, when it says Downloading 90GB or whatever, its not too! Sophon mode will verify all the files as it goes so it will say that when in the back it just verifies the game files and applies the necessary patches. 


Sorry for the confusion, we will fix the UX issue ASAP

**Comment by bagusnl** [comment]
Sophon update UI issues is partially mitigated in Stable and more advanced fixes (more stats available) in Preview

Let us know if you still have problem and thank you for your support <3
