### ISSUE TITLE
[Request]: Show 'What's New?' screen after forced updates

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#549]
### Is your request related to a problem?

No

### Describe your proposed solution

After forced updates, show update logs.

Ever since forced updates were implemented, the What's New screen will disappear before I even get to read a single bullet point as they are completed too quickly. How it is now defeats the whole point of having the What's New screen while updating (as you can't read the whole log in like 5 seconds lol).

If some people find the update logs annoying after each update, there could be a toggle which turns this feature on/off either in App Settings and/or in the update log page itself.

### Describe alternatives you've considered

Open the Github release after each update (which requires more clicks)

**Comment by bagusnl** [comment]
What about a function to show changelog in settings instead?

**Comment by bagusnl** [comment]
I have implemented the button for it that will open the changelog file hosted in our ReleaseRepo. Collapse will open it either in-app or external browser depending on your setting. 

![image](https://github.com/user-attachments/assets/6062bd44-7538-4247-932a-fada7d5ebf5b)

Let us know if this implementation is enough or you want to see more advanced markdown implementation (like the actual changelog shown when an update is pushed). The only drawback with that implementation is that no video view.

**Comment by bagusnl** [comment]
![image](https://github.com/user-attachments/assets/ed0a5462-5bd4-45b7-b974-c9a56c72b65b)

Something like this ?

**Comment by bagusnl** [comment]
Implemented in 1.81.1 https://github.com/CollapseLauncher/Collapse/releases/tag/CL-v1.81.1-pre
If you still have problem, reopen this ticket or open another one.

Thanks for the support <3
