### ISSUE TITLE
[Request]: We can still add  椰羊工具箱  site in the community tools of ZZZ

### ISSUE THREAD

**Issue by XieyilinMain** [CollapseLauncher/Collapse#561]
### Is your request related to a problem?

No

### Describe your proposed solution

We can add 椰羊工具箱 (https://cocogoat.work/extra/installer?type=nap_cn) entrance in community tools of ZZZ Mainland China version. Cocogoat.work is not only designed for Genshin Impact but also other HoYoGames.

### Describe alternatives you've considered

Ignore this issue.

**Comment by bagusnl** [comment]
Besides the installer zips page, I don't see any other tools for it yet. Tho, I'll add it anyway.

**Comment by Cryotechnic** [comment]
Updated in https://github.com/CollapseLauncher/CollapseLauncher-ReleaseRepo/commit/a458b1707c603be1d187bdfe3c61a030d3bd5abc
