### ISSUE TITLE
[Bug]: Blurred background persists after switching regions while on the Repair/Settings page

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#567]
### Affected Version

Collapse 1.81.4 Preview

### Bug Behavior

After going to a page that is different from the 'main game page' then switching regions, the launcher will go back to the 'main game page,' but the background blur will stay on the screen, not allowing you to see the background until you switch to a different page then back again.

### Expected Behavior

After the automatic switch back to the 'main game page,' the blur should disappear as well.

### Steps to reproduce

1. Go to the App Settings, Game Repair, Cache Repair, or Graphics Settings page
2. Switch regions or games

### Screenshot(s)

https://github.com/user-attachments/assets/77cbad96-6aa5-475e-b19a-ba774b9ee7fc

**Comment by Cactism** [comment]
wait what the heck why did the text on the 'switching game regions' pop up at the bottom disappear 💀

**Comment by bagusnl** [comment]
We love async

**Comment by Cactism** [comment]
Appears to be fixed in the latest Preview build!
https://github.com/CollapseLauncher/Collapse/releases/tag/CL-v1.82.0-pre
