### ISSUE TITLE
[Bug]: Game installation corrupted

### ISSUE THREAD

**Issue by Caelum008** [CollapseLauncher/Collapse#573]
### Affected Version

1.81.5-Pre

### Bug Behavior

Upon verification, a popup shows that says "One of the downloaded file is corrupted." then if tried to redownload, it downloads the whole preload package and the popup persists.

### Expected Behavior

Should verify and finish the preload downloading.

### Steps to reproduce

1. Restarted the app
2. Redownloaded the files

### Screenshot(s)

![image](https://github.com/user-attachments/assets/38ae794a-b2e7-42f1-9bc5-4af9d30924ae)

**Comment by Caelum008** [comment]
Switching to stable release worked.

**Comment by neon-nyan** [comment]
Hi there, 
Can you give us an info what 3 packages downloaded?

**Comment by Caelum008** [comment]
> Hi there, Can you give us an info what 3 packages downloaded?

Hi. I'm not really sure what files they were because whenever I click the "Yes, Redownload", it just redownloads the whole 12.66GB preload and the same popup appears during verification. I can't reproduce the problem anymore because I already updated the game. Sorry about that.

**Comment by bagusnl** [comment]
This should be fixed on the current preview 1.81.6. I will close this issue for now as me and neon can confirm that the fix is working. Shall it still or broken again, feel free to reopen or make a new issue.

Thanks for supporting Collapse Launcher!
