### ISSUE TITLE
[Bug]: Missing Icon Assets for Some Icons

### ISSUE THREAD

**Issue by EvilSquirrelGuy** [CollapseLauncher/Collapse#574]
### Affected Version

Collapse 1.81.5-PRE

### Bug Behavior

After updating from 1.81.4-pre to 1.18.5-pre, some icon assets seem to be missing, and show up as rectangles.

Missing Icons:
- Notification Bell when notifications are open
- Edit and button icons on playtime
- All icons apart from `Add to Steam` and `BWIKI` in Quick Settings
- All community tools icons
- Check for updates buttons (settings)
- Waifu2X info icon
- Window size icons
- Keyboard shortcuts icons
- Repository CDN icons

*There might be more but these were all the ones I was able to identify*

Log file: [log-2024-09-09-pre1.81.5-id1.log](https://github.com/user-attachments/files/16929382/log-2024-09-09-pre1.81.5-id1.log)

### Expected Behavior

Icons show up as they did before.

### Steps to reproduce

1. Open Collapse Preview 1.81.5-PRE
2. Open notification tray and look at the bell icon
3. Open all the buttons at the bottom right of the screen
4. Open application settings and scroll through them

### Screenshot(s)

![Game Launch UI with Community tools](https://github.com/user-attachments/assets/1f7a806e-0fd6-4fe7-a9c6-54da6e5d175b)

![Notification tab with button](https://github.com/user-attachments/assets/34f05d48-bdca-493e-bfd8-027ff4674b36)

![Quick Settings](https://github.com/user-attachments/assets/40892bb2-39ef-4a63-87ad-bc070a02d3f0)

![Waifu2X and Check for Updates buttons](https://github.com/user-attachments/assets/c0938438-4478-47aa-8a05-f8233ce29ad0)

![Window Size and Keyboard Shortcuts sections](https://github.com/user-attachments/assets/775ab487-8972-4c34-8994-b6df6bc95fa0)

![Repository CDN section](https://github.com/user-attachments/assets/a20c412e-db83-482d-8efc-32112490a96c)

![Keyboard shortcuts modal](https://github.com/user-attachments/assets/431cdb3f-b5d6-4f35-a774-fbcfb737af94)

### Additional Information

The provided screenshots only show Genshin Impact Global's Icon arrangement, however I've checked through a couple other games and regions to verify the extent of the issue (as far as possible).

- Honkai Impact 3rd - Global & Mainland China
- Genshin Impact - Global, Mainland China & Bilibili
- Honkai Star Rail - Global & Mainland China
- Zenless Zone Zero - Global & Mainland China

**Comment by bagusnl** [comment]
Issue successfully replicated in W10 environment (22H2)
Will try to find missing fonts

**Comment by EvilSquirrelGuy** [comment]
Issue seems to be resolved after updating to `1.81.6-pre`.
