### ISSUE TITLE
[Bug]: Is the radius of the arc endpoint of the outer circle of the update download progress bar asymmetrical?

### ISSUE THREAD

**Issue by DuckDeng** [CollapseLauncher/Collapse#581]
### Affected Version

1.80.19

### Bug Behavior

The endpoints of the outer circle arc are not smooth, it seems that the size of the superimposed circle is too large

### Expected Behavior

The endpoints of the outer arc should be smooth

### Steps to reproduce

none

### Screenshot(s)

![image](https://github.com/user-attachments/assets/28705699-01c9-4e5d-92c2-6f26f25b6d98)

**Comment by neon-nyan** [comment]
Hi @DuckDeng,

The outer progress bar appearance is actually intended since the blur grid above it overlays and should rays the acrylic effect if you enabled the acrylic blur effect in the app settings or system-wide.

**Comment by DuckDeng** [comment]
But there isn't a shadow effect on progress bar, it looks like the outer progress bar overlay on inner layer directly.

By the way, when I off `acrylic blur` ,there are some element can not display. Such as the `"speed" icon` and `"downloading" icon`.
![PixPin_2024-09-24_23-02-07](https://github.com/user-attachments/assets/b5001665-31e6-4ae8-a9d6-1701df49fe0c)

**Comment by neon-nyan** [comment]
> But there isn't a shadow effect on progress bar, it looks like the outer progress bar overlay on inner layer directly.
> 
Thanks for noticing. This effect should exist in upcoming preview release while we are still working on improving the UI bit-by-bit.

Regarding to that missing color for certain status element, we noticed that the "FallbackColor" for that certain element went missing, causing the color becoming transparent. Also, this issue should be fixed in the next preview release.

**Comment by neon-nyan** [comment]
As per no more confirmation, we are going to close this issue for now.
Feel free to reopen this issue if you still have any concern about this.
