### ISSUE TITLE
[Request]: Appearance of Audio languge choosing page

### ISSUE THREAD

**Issue by DuckDeng** [CollapseLauncher/Collapse#583]
### Is your request related to a problem?

No

### How is the feature request related to the problem?

skipped

### Describe your proposed solution

![PixPin_2024-09-24_23-03-44](https://github.com/user-attachments/assets/a1ceb16f-efda-4ff4-8f58-ebf90b9b1211)
The gray area will make people think that the item is not clickable, that is, "disabled state".

Maybe we can remove the gray layer, the layers are unnecessray.

### Describe alternatives you've considered

none

**Comment by Cryotechnic** [comment]
Fixed in the last couple of versions.
