### ISSUE TITLE
[Bug]: Crash on game change

### ISSUE THREAD

**Issue by Sloweneuh** [CollapseLauncher/Collapse#585]
### Affected Version

1.81.6-pre

### Bug Behavior

The launcher randomly crashes when changing game (haven't tried with region change).
It happens fairly often but I'm not sure if there's a pattern.
It displays the console with an error message, I added a screenshot.

### Expected Behavior

Should have switched displayed game.

### Steps to reproduce

1.[Open the launcher]
2.[Switch the displayed game]

### Screenshot(s)

<img width="716" alt="{5BD0B836-1950-4558-B142-6B86868C027B}" src="https://github.com/user-attachments/assets/bce36129-33fe-468d-b399-a44c217d841d">

### Additional Information

[log-2024-09-30-pre1.81.6-id0.log](https://github.com/user-attachments/files/17189128/log-2024-09-30-pre1.81.6-id0.log)
[DxDiag.txt](https://github.com/user-attachments/files/17189132/DxDiag.txt)

**Comment by bagusnl** [comment]
This _should_ be fixed on next preview, some black magic thing WinUI weird stuffy bit
