### ISSUE TITLE
[Request]: alternative download speed with planifer

### ISSUE THREAD

**Issue by zakidze** [CollapseLauncher/Collapse#591]
### Is your request related to a problem?

No

### How is the feature request related to the problem?

i want to example download on the day with speed of 2mbps and at night 10 mbps or max speed possible ( thoes speeds are editable global speed and alternative speed )

an input with  desierd alternative speed 

and also the time in day when the alternative speed executes and stop executing

hers an image example  (an image example)

https://user-images.githubusercontent.com/26369776/147144827-726d90b4-7e56-49c8-af09-4e44e251a069.PNG

### Describe your proposed solution

https://user-images.githubusercontent.com/26369776/147144827-726d90b4-7e56-49c8-af09-4e44e251a069.PNG

### Describe alternatives you've considered

-

### Additional context

-

**Comment by bagusnl** [comment]
Last warning: stop making new entry if the old one still exist
