### ISSUE TITLE
[Bug]: Genshin Crashes with Pre-launch commands

### ISSUE THREAD

**Issue by ASDKICKOFF** [CollapseLauncher/Collapse#592]
### Affected Version

1.80.19

### Bug Behavior

When i launch the game with pre-launch commands my game launched and turns off and then the launcher pop out.
I'll include the pre-launch commands below.

### Expected Behavior

Collapse should launch the game after executing the pre-launch commands.

### Steps to reproduce

1. download 3dmigoto and Collapse (both are in additional information, below), and install. 3dmigoto files should be in desktop\3dmigoto if you don't want to change step 5 directory
2. Open Collapse
3. set game to [genshin impact], change region to [Global] (game was downloaded from hoyoplay)
4. go to [game settings] (from collapse)
5. in advance settings (enable) enable pre-launch commands, and input the command [start cmd.exe @cmd /k "cd C:\Users\%USERPROFILE%\Desktop\3dmigoto && "3DMigotoLoader.exe" && exit"] without the []
6. Apply settings (delay doesn't affect the process for me, that's why i didn't mention it)
7. go to [Launcher]
8. Start game
9. i heard beep beep-boop beep-boop and then launcher pops out.

### Related Issues

#580

### Additional Information

[DxDiag.txt](https://github.com/user-attachments/files/17345434/DxDiag.txt)
[Collapse](https://github.com/CollapseLauncher)
[3dmigoto](https://github.com/SilentNightSound/GI-Model-Importer)
I have tried repairing the game it does not fix this bug; bug only work with pre-launch commands enabled if disabled then game works just fine.

**Comment by studiobutter** [comment]
I don't mod Genshin, but the problem is 3dmigoto is executing from a directory that doesn't have the necessary dlls.

Try creating a batch file with the following
```
@echo off
cd [Directory where 3dmigoto executable is]
"3DMigoto Loader.exe"
```
Save as [name].bat
(Example: 3dlaunch.bat)

In the pre-launch commands
```
[Path to Batch]
```
Example:
```
C:\CLI\3dlaunch.bat
```

Put quotes if the folders or executable have space

**Comment by studiobutter** [comment]
Just a heads up. We are not responsible for anything happens on your account

**Comment by studiobutter** [comment]
I forgot to mention that if you currently have any 3dmigoto instance running, kill it with this command
```
taskkill /f /im "3DMigoto Loader.exe"
```

Admin is required.
(Windows 11 24H2 can use `sudo` to run any admin commands)
