### ISSUE TITLE
[Bug]: Launcher crash when opening launcher settings on native aot build

### ISSUE THREAD

**Issue by anggerbudi** [CollapseLauncher/Collapse#593]
### Affected Version

Collapse Native AOT build 1.81.7

### Bug Behavior

The app is crashing / force close when pressing the launcher settings button

### Expected Behavior

It should open the launcher settings page

### Steps to reproduce

1. Open collapse launcher
2. Press launcher setting button on the bottom left (gear icon)
3. App force close

### Additional Information

[DxDiag.txt](https://github.com/user-attachments/files/17474904/DxDiag.txt)

[log-2024-10-22-pre1.81.7-id1.log](https://github.com/user-attachments/files/17474908/log-2024-10-22-pre1.81.7-id1.log)

[Collapse_Crash_Event-Viewer_Application Error.txt](https://github.com/user-attachments/files/17474946/Collapse_Crash_Event-Viewer_Application.Error.txt)
[Collapse_Crash_Event-Viewer_Windows Error Reporting.txt](https://github.com/user-attachments/files/17474947/Collapse_Crash_Event-Viewer_Windows.Error.Reporting.txt)

**Comment by bagusnl** [comment]
CI builds currently a bit borked for some reason, @neon-nyan publishes AoT test builds occasionally in Discord announcement channel if you want to try.

**Comment by anggerbudi** [comment]
> CI builds currently a bit borked for some reason, @neon-nyan publishes AoT test builds occasionally in Discord announcement channel if you want to try.

Yes i know, i think opening gh issue is better for issue tracking ?, I already told neon too about it

**Comment by anggerbudi** [comment]
Fixed on https://github.com/CollapseLauncher/Collapse/commit/042caaba4a553b5bbc94ecec315557f4c4af27a6
