### ISSUE TITLE
[Bug]: Unexpected way to unfold the menu

### ISSUE THREAD

**Issue by Miaoyww** [CollapseLauncher/Collapse#605]
### Affected Version

1.80.19 Stable

### Bug Behavior

see video

https://github.com/user-attachments/assets/f4e15954-700f-47ab-be39-429552c11624

### Expected Behavior

prevent title bar content from appearing
prevent the click event from passing through the webview page

### Steps to reproduce

see video

**Comment by bagusnl** [comment]
Can replicate on latest debug 
![image](https://github.com/user-attachments/assets/38462dc5-f73b-42e7-b6ef-66d75b217b49)

**Comment by neon-nyan** [comment]
This issue should be fixed in this commit: https://github.com/CollapseLauncher/Collapse/commit/d8045d12de98ab4708284bac01a4c18be262a460
I will keep this issue open until the next stable release

**Comment by neon-nyan** [comment]
This issue has been fixed on both stable & preview 1.82.8 release. Closing this issue for now.
