### ISSUE TITLE
[Bug]: Mouse inputs not working

### ISSUE THREAD

**Issue by heyitzrare** [CollapseLauncher/Collapse#610]
### Affected Version

Collapse 1.80.19

### Bug Behavior

Upon opening the launcher, the mouse cursor temporarily enters the "Busy" state, and no inputs (clicks or hovers) provide any sort of response within the launcher. It is still possible to move the launcher to another display, and keyboard inputs still function as intended.

### Expected Behavior

Clicking on or hovering over UI elements should provide some response.

### Steps to reproduce

1. Open Collapse Launcher
2. Observe that the mouse does not activate UI elements

### Screenshot(s)

![mouse non functional](https://github.com/user-attachments/assets/959c6550-63e8-43bc-bbf6-57dcaac44ac4)

### Additional Information

DxDiag: [DxDiag.txt](https://github.com/user-attachments/files/17903771/DxDiag.txt)
Collapse Log: [log-2024-11-25-sta1.80.19-id1.log](https://github.com/user-attachments/files/17903729/log-2024-11-25-sta1.80.19-id1.log)

**Comment by heyitzrare** [comment]
UPDATE: Upon further investigation, this does not appear to be exclusive to Collapse, as it's occurring with many other UWP-style apps as well. This appears to be a relatively common bug related to UWP apps and mouse drivers (potentially a Razer issue?) - uninstalling and reinstalling said mouse driver fixed the issue, at least for now. Posting this here in case anyone else has this issues.

**Comment by bagusnl** [comment]
Thanks for the insight, noted!
