### ISSUE TITLE
[Bug]: Collapse Launcher unable to extract Honkai Impact 3rd update

### ISSUE THREAD

**Issue by Seiko-Senpai** [CollapseLauncher/Collapse#612]
### Affected Version

1.80.0-1.82.3

### Bug Behavior

Whenever i try to update HI3 the extraction will get so far into it and then crash collapse
i have already tried deleting the update and reinstalling it and the same issue applies
![image](https://github.com/user-attachments/assets/c2481f41-6c25-4a77-9ce4-f2e1bab12ab4)

### Expected Behavior

the update to extract 

### Steps to reproduce

download update

### Additional Information

on the beta build

**Comment by bagusnl** [comment]
Check TaskManager and see if the HDD usage is present. If it does, simply let the process to finish up. This bug technically only repeatable by others in 1.82.0 with NativeAOT build, but on harder cases it might cause UI lockups on other version. Cant tell much without knowing much you Windows system and any of modification done to it

**Comment by neon-nyan** [comment]
This issue has been fixed on the latest stable and preview version (1.82.8).
We have revert back the compilation method from NativeAOT to IL-based one. Closing this issue as it's now fixed.
