### ISSUE TITLE
[Bug]: Duplicate desktop icon after updating Collapse Preview

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#630]
### Affected Version

Collapse 1.82.6 Preview

### Bug Behavior

After an update, Collapse Launcher will create a duplicate desktop shortcut. I believe that this has been an issue for me ever since Preview v[1.82.3](https://github.com/CollapseLauncher/Collapse/releases/tag/CL-v1.82.3-pre) due to the new update system possibly(?)

### Expected Behavior

Collapse should not have created a duplicate desktop shortcut.

### Steps to reproduce

1. Install [1.82.6 Preview](https://github.com/CollapseLauncher/Collapse/releases/tag/CL-v1.82.6-pre)
2. Wait until the update prompt shows up
3. Update
4. Close Collapse Launcher
5. Refresh desktop

### Screenshot(s)

https://github.com/user-attachments/assets/0e50bd6f-4d3c-4ce2-baa2-b9e6373d606b

Both shortcuts are exactly the same thing:
![image](https://github.com/user-attachments/assets/d864862c-3f28-4b48-b188-ffe1ee26d7dc)

**Comment by bagusnl** [comment]
This is already fixed in 1.82.7 so you're safe to delete the one shortcut coming from Public user

**Comment by Cactism** [comment]
I see; I didn't know that (the time I miss the update logs too)
