### ISSUE TITLE
[Bug]: Closing Collapse from the taskbar doesn't work as expected

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#631]
### Affected Version

Collapse 1.82.7 Preview

### Bug Behavior

Clicking the `Close Window` buttons when you hover over (or right click) Collapse in the taskbar doesn't have any effect.

### Expected Behavior

The buttons should have the same behavior as other applications: closing/exiting Collapse like the :x: button would on the launcher window

### Steps to reproduce

1. Hover over Collapse in the taskbar
2. Click the :x: button
3. Nothing happens
and
1. Right click Collapse in the task bar
2. Click `Close Window`
3. Nothing happens

### Screenshot(s)

https://github.com/user-attachments/assets/64ff5b40-03d2-4d96-86a6-609bcc70614b

**Comment by shatyuka** [comment]
Expected to be fixed in commit e8b9b6f.
Try this CI build: https://nightly.link/CollapseLauncher/Collapse/actions/runs/12433858407

**Comment by Cactism** [comment]
@shatyuka Both builds appear to work!

**Comment by neon-nyan** [comment]
This issue has been fixed in both stable & preview 1.82.8. Closing this issue for now.
