### ISSUE TITLE
[Request]: Always offer native desktop resolution for ZZZ

### ISSUE THREAD

**Issue by BobbyWibowo** [CollapseLauncher/Collapse#632]
### Is your request related to a problem?

No

### Describe your proposed solution

My desktop's native resolution is 2560x1600 (16:10), but Collapse would only offer some standard 16:9 resolutions, which I presume is because the game itself only offers these resolutions,
<details>

![image](https://i.imgur.com/2gEhC1Q.png)
</details>
But as can be seen on the screenshot below, the game does allow picking a so-called Default option, which is the desktop's native resolution, even if it isn't 16:9,
<details>

![image](https://i.imgur.com/qZIM1o5.png)
</details>

At the moment, Collapse will also default to blank "Select" option when using in-game's Default resolution,
<details>

![image](https://i.imgur.com/i6rjyzA.png)
</details>

### Describe alternatives you've considered

Not a big deal, honestly, since changing other graphic options through Collapse seemingly will not mess with resolution regardless.

But assuming you want to go back to native resolution, you'd then always have to use the in-game option.

### Additional context

And more like, resolution option in Collapse seemingly does not work at all on my end. The game would always reset to native resolution, but using in-game's resolution option does work fine.

No issue with changing other graphic options though (vsync, shadows, and all the jazz).

I'm on Collapse **1.82.7 Preview**.

**Comment by bagusnl** [comment]
Heyya!
Can you send us your GENERAL_DATA.bin file found in ZenlessZoneZero_Data\Persistent\LocalStorage ?

Though, since it does contain your UID, if you don't want to share it to everyone else, you can email them to bagusnl+collapse@protonmail.com

**Comment by BobbyWibowo** [comment]
@bagusnl Sent!

**Comment by bagusnl** [comment]
Implemented in 1.82.9
