### ISSUE TITLE
[Bug]: 1.82.8 无法启动

### ISSUE THREAD

**Issue by jfaaaa** [CollapseLauncher/Collapse#636]
### Affected Version

1.82.8

### Bug Behavior

1.82.8 无法启动，不管是便携版还是安装版。老版本能运行
![image](https://github.com/user-attachments/assets/af37ddd1-235c-4d13-bb9a-c7a01f454128)
![image](https://github.com/user-attachments/assets/f2849883-aa3c-4e27-8443-20406a474174)
![image](https://github.com/user-attachments/assets/4855a075-430b-4fb9-b33e-75de4061b692)
![image](https://github.com/user-attachments/assets/71cfe3d4-a6b6-4561-9a6e-2de9d9fce722)
![image](https://github.com/user-attachments/assets/4f87628d-dd22-4699-978c-b0a3472ff44f)

### Expected Behavior

Installer
[update:11444] [18:23:47] [INFO] --
[update:11444] [18:23:47] [INFO] Starting Velopack Updater (0.0.1015)
[update:11444] [18:23:47] [INFO]     Location: C:\Users\Administrator\AppData\Local\CollapseLauncher\Update.exe
[update:11444] [18:23:47] [INFO]     CWD: C:\Users\Administrator\AppData\Local\CollapseLauncher
[update:11444] [18:23:47] [INFO]     Verbose: false
[update:11444] [18:23:47] [INFO]     Silent: false
[update:11444] [18:23:47] [INFO]     Log File: None
[update:11444] [18:23:47] [ERROR] An error has occurred: No known subcommand was used. Try `--help` for more information.

Portable
[stub:10736] [18:29:46] [INFO] --
[stub:10736] [18:29:46] [INFO] Starting Velopack Stub (at "E:\\CollapseLauncher\\CollapseLauncher.exe")
[stub:10736] [18:29:46] [INFO] Stub about to start Update.exe (E:\CollapseLauncher\Update.exe) with args: ["start", "--"]
[update:14984] [18:29:46] [INFO] --
[update:14984] [18:29:46] [INFO] Starting Velopack Updater (0.0.1015)
[update:14984] [18:29:46] [INFO]     Location: E:\CollapseLauncher\Update.exe
[update:14984] [18:29:46] [INFO]     CWD: E:\CollapseLauncher
[update:14984] [18:29:46] [INFO]     Verbose: false
[update:14984] [18:29:46] [INFO]     Silent: false
[update:14984] [18:29:46] [INFO]     Log File: None
[update:14984] [18:29:46] [INFO] Command: Start
[update:14984] [18:29:46] [INFO]     Wait: NoWait
[update:14984] [18:29:46] [INFO]     Exe Name: None
[update:14984] [18:29:46] [INFO]     Exe Args: None
[update:14984] [18:29:46] [INFO] Auto-locating app manifest...
[update:14984] [18:29:46] [INFO] About to launch: '"E:\\CollapseLauncher\\current\\CollapseLauncher.exe"' in dir '"E:\\CollapseLauncher\\current"'
[DxDiag.txt](https://github.com/user-attachments/files/18228276/DxDiag.txt)

### Steps to reproduce

.

**Comment by bagusnl** [comment]
You run the CollapseLauncher.exe inside the current folder instead

**Comment by jfaaaa** [comment]
![image](https://github.com/user-attachments/assets/9a52b904-3c85-4569-833d-f5d35bbf2e0b)
![image](https://github.com/user-attachments/assets/d52e4736-c76d-4341-896b-67918eb38c3b)
![image](https://github.com/user-attachments/assets/b8235a4b-503a-45ba-8e32-bcd44828320f)
![image](https://github.com/user-attachments/assets/64af76bb-a624-4a04-96a3-78ef96f22c18)

都无法启动

**Comment by shatyuka** [comment]
plz send your launcher log here

**Comment by jfaaaa** [comment]
[Velopack.log](https://github.com/user-attachments/files/18231584/Velopack.log)
[log-2024-12-24-pre1.82.0-id1.log](https://github.com/user-attachments/files/18231585/log-2024-12-24-pre1.82.0-id1.log)
[log-2024-12-24-sta1.80.16-id0.log](https://github.com/user-attachments/files/18231586/log-2024-12-24-sta1.80.16-id0.log)
好像也没看见其他的日志

**Comment by shatyuka** [comment]
1.82.8的呢

**Comment by jfaaaa** [comment]
解决了 系统更新到win10 22h2就打开了
