### ISSUE TITLE
[Bug|Fix Available]: Collapse couldn't open after 1.82.8 update to 1.82.9

### ISSUE THREAD

**Issue by LandMineCube** [CollapseLauncher/Collapse#642]
### Affected Version

Collapse 1.82.9

### Bug Behavior

When I open the old version (1.82.8), it automatic update to 1.82.9, but the install directory  does not see the latest-version's file.
If open the shortcut at destop, it will show the error window.
there also have a strange thing...double click the ApplyUpdate.exe, it will download the 1.82.8 version
![QQ20241225-221048](https://github.com/user-attachments/assets/27ad4494-b166-44dd-97ea-311f6a599438)

![1234](https://github.com/user-attachments/assets/ee7e8545-ba16-4398-a6ec-550b8d11d427)

### Expected Behavior

correct install the latest version

### Steps to reproduce

open the old version, waiting it automatic update, them boom.

**Comment by bagusnl** [comment]
that apply update seems to be downloading just fine, can you tell us where Collapse is installed in your system ?

**Comment by LandMineCube** [comment]
> that apply update seems to be downloading just fine, can you tell us where Collapse is installed in your system ?

I found that one image didn't update correctly, I try to upload again. it will show the intall dircetory.
Only the drive partition is Chinese name

**Comment by bagusnl** [comment]
Ah noted, can you try to run the CollapseLauncher.exe inside the current folder instead of the one outside?

**Comment by 1347435814** [comment]
我也有这个bug，删掉直接装最新版就可以了

**Comment by LandMineCube** [comment]
> 我也有这个bug，删掉直接装最新版就可以了

话是这么说，我还是寻思提交一下，我看着感觉像自动更新的问题，提交修了免得后续更新又得手动下载安装包

**Comment by Borziking** [comment]
> Ah noted, can you try to run the CollapseLauncher.exe inside the current folder instead of the one outside?

Nothing, same error

**Comment by LandMineCube** [comment]
> Ah noted, can you try to run the CollapseLauncher.exe inside the current folder instead of the one outside?

Same as open the shortcut.
I found three log files in the folder, I will upload it.
[Velopack.log](https://github.com/user-attachments/files/18246475/Velopack.log)
[Squirrel.log](https://github.com/user-attachments/files/18246476/Squirrel.log)
[Squirrel-ProcessStart.log](https://github.com/user-attachments/files/18246477/Squirrel-ProcessStart.log)

Also I found that if I install the 1.82.9 version with the package instead of use automatic update, it can run normally, I think the problem may in the update program

**Comment by neon-nyan** [comment]
Can you try remove any files except the .betaId inside of the "package" folder and try run the main executable inside of the "current" folder?
![image](https://github.com/user-attachments/assets/c14dd315-1315-45c1-a600-34db81cc7fd4)

**Comment by neon-nyan** [comment]
In other hand, we are currently trying to fix the issue. This might take a while and if your issue still persist, we suggest you to reinstall the launcher and try cleaning up any files inside the previous installation folder.

[Stable Installer](https://github.com/CollapseLauncher/Collapse/releases/download/CL-v1.82.9/CollapseLauncher-stable-Setup.exe)
[Preview Installer](https://github.com/CollapseLauncher/Collapse/releases/download/CL-v1.82.9-pre/CollapseLauncher-preview-Setup.exe)

> Note:
> Reinstalling won't destroy your previous game installation

**Comment by LandMineCube** [comment]
> Can you try remove any files except the .betaId inside of the "package" folder and try run the main executable inside of the "current" folder?
> 
> ![image](https://private-user-images.githubusercontent.com/30566970/398585154-c14dd315-1315-45c1-a600-34db81cc7fd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDEyMzAsIm5iZiI6MTczNTE0MDkzMCwicGF0aCI6Ii8zMDU2Njk3MC8zOTg1ODUxNTQtYzE0ZGQzMTUtMTMxNS00NWMxLWE2MDAtMzRkYjgxY2M3ZmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDE1MzUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMjdjNmUwN2QyZTZiYTRhMzc2MTdhNGE1NmU2NDVmOTkxMDEzMTdmMjg3NzViZDE4ZmVlMjBiZTE5OTU1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CguqtPS3sO_7HdesFHxWh4mg_VCzAkhrovpfsCIqTVk)

When the files that you refers are removed, Collpase can open as normal, but it will update soon. I will reinstall it as you said.

**Comment by neon-nyan** [comment]
Heyo!
We just pushed our ``ApplyUpdate.exe`` payload to the CDN.
Just in case someone needs a help without involving installation of the launcher, here's the step you can follow:

1. Download the **ApplyUpdate.exe** payload [**Here**](https://github.com/CollapseLauncher/CollapseLauncher-ReleaseRepo/raw/refs/heads/main/ApplyUpdate.exe)
2. Copy the executable inside of your launcher installation folder (For example: C:\Program Files\Collapse Launcher\)
![image](https://github.com/user-attachments/assets/40d2ad59-6eb8-43be-9664-9aad13dc2a95)
3. Run the "ApplyUpdate.exe" executable as Administrator.
4. Click on "Update Now!" button.
![image](https://github.com/user-attachments/assets/89e6452f-0a2e-40d3-8c95-f25d1333c541)
5. If you get "Broken Existing Installation Detected" message, click on "Yes"
![image](https://github.com/user-attachments/assets/8dee8ff3-9aee-4642-8c0c-b753fb93bfed)
6. Wait until it finishes the update and the launcher should be opened after the update.
![image](https://github.com/user-attachments/assets/74f79bf0-9fa9-4618-b725-f66318d6106c)

**Comment by EVOIndra** [comment]
updating using ApplyUpdate.exe still forces you to update within the launcher, which always ends up with the aforementioned error

**Comment by neon-nyan** [comment]
Can you share me screenshots of the files inside your installation folder? @EVOIndra
Both on C:\Program Files\Collapse Launcher and C:\Program Files\Collapse Launcher\packages

**Comment by EVOIndra** [comment]
![2](https://github.com/user-attachments/assets/d91683db-764c-4bdf-bdd7-c35aa3282937)
![1](https://github.com/user-attachments/assets/4b2b1395-0e4a-4403-9526-f70c437b2928)
here are the screenshots, I tried updating through the launcher itself and using ApplyUpdate.exe, same result

**Comment by neon-nyan** [comment]
> ![2](https://private-user-images.githubusercontent.com/192820518/398594552-d91683db-764c-4bdf-bdd7-c35aa3282937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNTE5NzgsIm5iZiI6MTczNTE1MTY3OCwicGF0aCI6Ii8xOTI4MjA1MTgvMzk4NTk0NTUyLWQ5MTY4M2RiLTc2NGMtNGJkZi1iZGQ3LWMzNWFhMzI4MjkzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxODM0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjI2YmQ2YWUxMTczNmE2NTE0NDBlYjU2NDI3ZGMzMjk0OTNmYjdmZGUyMGU0NDkzODMxZDQ0MTc5MTc1MzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tUM2-N0YslkilUNLFHcSGQAmU3L4ykhM6j2Az8RXNGo) ![1](https://private-user-images.githubusercontent.com/192820518/398594554-4b2b1395-0e4a-4403-9526-f70c437b2928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNTE5NzgsIm5iZiI6MTczNTE1MTY3OCwicGF0aCI6Ii8xOTI4MjA1MTgvMzk4NTk0NTU0LTRiMmIxMzk1LTBlNGEtNDQwMy05NTI2LWY3MGM0MzdiMjkyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxODM0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGExMjVjNWIyN2Q1ZDFkMjc3OWY0ODI2ODczODc2OGU5MmQ0YjZiMDBlM2E5MTg2ZTk5MGMxMDZhZjczN2NiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XQookwxLuy6Y12mtxUK-224f50-6F6UYy1zmX9plxC0) here are the screenshots, I tried updating through the launcher itself and using ApplyUpdate.exe, same result

Seems like you haven't downloaded the "ApplyUpdate.exe" executable from the instruction above since the size is different.
Can you try download the new one and then run it?

The link is in the first step:
![image](https://github.com/user-attachments/assets/82a532c9-b590-4700-a165-c98d2273f80b)

**Comment by EVOIndra** [comment]
it worked, thank you very much ^^

**Comment by xFataL** [comment]
Hello. The Collapse Launcher executable was gone after applying the update. Do I need to run the apply update every time to launch Collapse?
![image](https://github.com/user-attachments/assets/473b5c44-ceda-49bb-8b22-e14390a222eb)

**Comment by bagusnl** [comment]
@xFataL the one you want to launch should be inside the "current" folder ^^

**Comment by xFataL** [comment]
> @xFataL the one you want to launch should be inside the "current" folder ^^

Ohhh thank you!

**Comment by TheGokki** [comment]
Had same issue, the ApplyUpdate was looping the .8 version instead of .9 and causing errors. I had to manually download the latest payload for it to properly apply the .9.

Regular users that don't visit this thread will be stuck.

**Comment by Aalivexy** [comment]
After manually running ApplyUpdate.exe I upgraded to 1.82.9, everything else was fine, but running CollapseLauncher.exe directly did not open the app. Running CollapseLauncher.exe in the current folder worked fine, maybe this is another issue?

**Comment by MH-Leon** [comment]
ApplyUpdate.exe failed to install the update.
I downloaded the ApplyUpdate.exe provided in this thread and overwrote the original
![屏幕截图 2024-12-27 071116](https://github.com/user-attachments/assets/e5d92ea9-3ab2-4c48-892f-e1d143d7f0da)
The Collapse Launcher installation directory contains these files after the download is complete.
![屏幕截图 2024-12-27 071134](https://github.com/user-attachments/assets/896167ff-ad9b-42bc-88c0-091302a0c2bc)
Run the "ApplyUpdate.exe", get "Broken Existing Installation Detected" message, then I click on "Yes"
After the progress bar runs, I get this error message.
![屏幕截图 2024-12-27 071203](https://github.com/user-attachments/assets/280795c7-9ee9-4454-93b7-54c283454992)

**Comment by bagusnl** [comment]
@MH-Leon try restarting your system then run ApplyUpdate as admin
Seems like the file is locked which usually Windows issue

**Comment by MH-Leon** [comment]
> 尝试重新启动系统，然后以管理员身份运行 ApplyUpdate似乎文件已被锁定，这通常是 Windows 问题

The downloaded ApplyUpdate.exe was working fine, I didn't close the running Collapse Launcher first which caused the file to be locked.
Now the .8 version starts up fine

**Comment by neon-nyan** [comment]
This issue should have been fixed in the latest hotfix (1.82.10) for both stable and preview channel.
Closing this issue for now. Feel free to re-open this issue if you have this issue still occur.
