### ISSUE TITLE
In Windows after closing the screen / sleep download speed will not update

### ISSUE THREAD

**Issue by GuangChen2333** [CollapseLauncher/Collapse#92]
### Enviroment
Windows: 10.0.19045.2604
Collapse: 1.0.69.4 Preview

### Description
In Windows after closing the screen / sleep download speed will not update

The total progress and left time will update normally

Should I upload some log files :(

**Comment by neon-nyan** [comment]
> Should I upload some log files :(

Hi @GuangChen2333,
Yes, please provide some logs so we can investigate further

**Comment by GuangChen2333** [comment]
https://drive.google.com/file/d/1KTT-cmgGrQJO0ux8gyOpvmtljZDqkjrg/view?usp=share_link

**Comment by bagusnl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [System sleep causes issue in downloading](https://trello.com/c/qezyjQ4U/11-system-sleep-causes-issue-in-downloading)

**Comment by bagusnl** [comment]
Hi, we still haven't figure the S3 sleep issue as its really hard to reproduce. But we have implemented a workaround that prevent system from sleeping when Collapse is doing important stuff like downloading etc.

I hope this is good enough for now and feel free to reopen the ticket if there are new details about this issue or other possible workarounds.

Sorry for taking so long and thanks for reporting the issue <3
